'use client';
import {useEffect,useRef,useState} from 'react';
import {Activity,Plus,Download,Undo2,Check,X,Users,BarChart3,ClipboardList,ChevronRight,Target,Share2,Grip,Flag,Trash2,Loader2,RotateCw} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {makePDF,download} from '@/lib/pdf';
type Sport='volei'|'basquete'|'futebol';
type Player={id:string;name:string;number:string;position:string;x:number;y:number;active:boolean};
type Event={id:string;player:string;action:string;result:'success'|'error'|'neutral';time:string;period:string};
type Match={id:string;sport:Sport;team:string;opponent:string;date:string;players:Player[];events:Event[];finished:boolean;period:string;score:[number,number]};
type Data={matches:Match[]};
const sports:Record<Sport,{name:string;icon:string;count:number;actions:string[];neutral:string[];period:string}>={volei:{name:'Vôlei',icon:'◉',count:6,actions:['Saque','Ataque','Recepção','Bloqueio','Levantamento','Defesa'],neutral:[],period:'Set'},basquete:{name:'Basquete',icon:'◉',count:5,actions:['Arremesso de 2','Arremesso de 3','Lance livre','Passe'],neutral:['Rebote','Assistência','Roubo de bola','Falta','Perda de bola'],period:'Quarto'},futebol:{name:'Futebol',icon:'◉',count:11,actions:['Finalização','Passe','Desarme','Cruzamento'],neutral:['Gol','Assistência','Defesa do goleiro','Falta','Perda de bola'],period:'Tempo'}};
const uid=()=>crypto.randomUUID();
const initial:Data={matches:[]};
const pct=(a:number,b:number)=>b?Math.round(a/b*100):0;
function Picker({value,onChange,options,label}:{value:string;onChange:(s:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
function Court({sport,players,selected,onSelect,onMove,drawing}:{sport:Sport;players:Player[];selected:string;onSelect:(s:string)=>void;onMove:(id:string,x:number,y:number)=>void;drawing:boolean}){
 const ref=useRef<SVGSVGElement>(null);const drag=useRef<string|null>(null);const start=useRef<{x:number;y:number}|null>(null);const [paths,setPaths]=useState<string[]>([]);const [path,setPath]=useState('');
 const point=(e:React.PointerEvent)=>{const r=ref.current!.getBoundingClientRect();return {x:Math.max(5,Math.min(95,(e.clientX-r.left)/r.width*100)),y:Math.max(5,Math.min(95,(e.clientY-r.top)/r.height*100))};};
 return <div className="court-wrap"><svg ref={ref} viewBox="0 0 600 430" className={'court '+sport} aria-label={'Prancheta de '+sports[sport].name} onPointerDown={e=>{if(drawing){const p=point(e);setPath(`M${p.x*6} ${p.y*4.3}`);start.current=p;e.currentTarget.setPointerCapture(e.pointerId);}}} onPointerMove={e=>{if(drag.current){const p=point(e);onMove(drag.current,p.x,p.y);}else if(drawing&&start.current){const p=point(e);setPath(s=>s+` L${p.x*6} ${p.y*4.3}`);}}} onPointerUp={()=>{drag.current=null;start.current=null;if(path){setPaths(p=>[...p,path]);setPath('');}}} onPointerCancel={()=>{drag.current=null;start.current=null;setPath('');}}>
 <defs><pattern id="grain" width="22" height="22" patternUnits="userSpaceOnUse"><path d="M0 0h22" stroke="white" strokeOpacity=".018"/></pattern></defs><rect width="600" height="430" fill="url(#grain)"/><g fill="none" stroke="#c6ded1" strokeWidth="2" opacity=".7"><rect x="44" y="32" width="512" height="366"/>{sport==='volei'?<><path d="M44 215h512M44 154h512M44 276h512"/><path d="M30 215h540" strokeDasharray="5 5" strokeWidth="4"/></>:sport==='basquete'?<><path d="M300 32v366"/><circle cx="300" cy="215" r="52"/><path d="M44 151h105v128H44M556 151H451v128h105"/><circle cx="149" cy="215" r="64"/><circle cx="451" cy="215" r="64"/><path d="M44 71h42Q290 215 86 359H44M556 71h-42Q310 215 514 359h42"/><circle cx="70" cy="215" r="9"/><circle cx="530" cy="215" r="9"/></>:<><path d="M300 32v366"/><circle cx="300" cy="215" r="52"/><path d="M44 115h86v200H44M556 115h-86v200h86M44 169h36v92H44M556 169h-36v92h36"/><path d="M130 177q48 38 0 76M470 177q-48 38 0 76"/></>}</g><g fill="none" stroke="#b8ef5b" strokeWidth="4" strokeLinecap="round">{paths.map((p,i)=><path key={i} d={p}/>)}{path&&<path d={path}/>}</g>
 {players.filter(p=>p.active).map(p=><g key={p.id} transform={`translate(${p.x*6},${p.y*4.3})`} role="button" tabIndex={0} aria-label={`Selecionar ${p.name}, número ${p.number}`} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')onSelect(p.id);}} onPointerDown={e=>{if(drawing)return;e.stopPropagation();onSelect(p.id);drag.current=p.id;e.currentTarget.setPointerCapture(e.pointerId);}} className="player-marker"><circle r={selected===p.id?24:21} fill={selected===p.id?'#b8ef5b':'#f4f8f6'} stroke={selected===p.id?'#e2ffb1':'#33554a'} strokeWidth="3"/><text textAnchor="middle" y="5" fontSize="16" fontWeight="800" fill="#19382d">{p.number}</text><text textAnchor="middle" y="39" fill="#fff" fontSize="14" fontWeight="500">{p.name.split(' ')[0].slice(0,14)}</text></g>)}</svg><div className="court-footer"><span><Grip size={14}/> Toque para selecionar · arraste para posicionar</span>{paths.length>0&&<button onClick={()=>setPaths([])}>Limpar desenhos</button>}</div></div>;
}
export default function Home(){
 const [data,setData]=useState<Data>(initial),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selectedMatch,setSelectedMatch]=useState(''),[selected,setSelected]=useState(''),[tab,setTab]=useState('prancheta'),[sport,setSport]=useState<Sport>('volei'),[setup,setSetup]=useState(false),[playerModal,setPlayerModal]=useState(false),[editId,setEditId]=useState(''),[team,setTeam]=useState(''),[opponent,setOpponent]=useState(''),[name,setName]=useState(''),[number,setNumber]=useState(''),[position,setPosition]=useState(''),[action,setAction]=useState('Saque'),[drawing,setDrawing]=useState(false),[notice,setNotice]=useState(''),[reportPlayer,setReportPlayer]=useState('team');
 const revisionRef=useRef(0),dataRef=useRef(data);dataRef.current=data;
 const m=data.matches.find(m=>m.id===selectedMatch)||data.matches[0];const spec=sports[m?.sport||sport];const athlete=m?.players.find(p=>p.id===selected);const events=m?.events||[];const success=events.filter(e=>e.result==='success').length,errors=events.filter(e=>e.result==='error').length,total=success+errors;
 useEffect(()=>{fetch('/api/state').then(async r=>{const v=await r.json() as {data?:Data;revision:number;error?:string};if(!r.ok)throw new Error(v.error);setData(v.data||initial);revisionRef.current=v.revision;setRevision(v.revision);if(v.data?.matches?.[0]){setSelectedMatch(v.data.matches[0].id);setSelected(v.data.matches[0].players[0]?.id||'');setAction(sports[v.data.matches[0].sport as Sport].actions[0]);}}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function save(next:Data){if(busy||loading)return false;setBusy(true);setError('');try{const r=await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:next,revision:revisionRef.current})});const v=await r.json() as {data?:Data;revision:number;error?:string};if(!r.ok)throw new Error(v.error);setData(next);revisionRef.current=v.revision;setRevision(v.revision);return true;}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.');return false;}finally{setBusy(false);}}
 function update(match:Match){return save({...dataRef.current,matches:dataRef.current.matches.map(x=>x.id===match.id?match:x)});}
 function switchMatch(id:string){const x=data.matches.find(m=>m.id===id)!;setSelectedMatch(id);setSelected(x.players[0]?.id||'');setAction(sports[x.sport].actions[0]);setReportPlayer('team');}
 async function create(e:React.FormEvent){e.preventDefault();const x:Match={id:uid(),sport,team:team.trim(),opponent:opponent.trim()||'Treino',date:new Date().toISOString(),players:[],events:[],finished:false,period:'1',score:[0,0]};if(await save({matches:[x,...data.matches]})){setSelectedMatch(x.id);setSelected('');setAction(sports[sport].actions[0]);setSetup(false);setTab('prancheta');setReportPlayer('team');}}
 async function addPlayer(e:React.FormEvent){e.preventDefault();if(!m)return;if(m.players.some(p=>p.number===number.trim()&&p.id!==editId)){setNotice('Esse número já está em uso na equipe.');return;}const i=m.players.filter(p=>p.active).length;const active=i<spec.count;const p:Player={id:editId||uid(),name:name.trim(),number:number.trim(),position:position.trim(),x:m.sport==='volei'?25+(i%3)*25:20+(i%4)*20,y:m.sport==='volei'?36+Math.floor(i/3)*35:25+Math.floor(i/4)*25,active};const players=editId?m.players.map(a=>a.id===editId?{...a,name:p.name,number:p.number,position:p.position}:a):[...m.players,p];if(await update({...m,players})){setSelected(p.id);setPlayerModal(false);setNotice('Atleta salvo.');}}
 function openPlayer(p?:Player){setEditId(p?.id||'');setName(p?.name||'');setNumber(p?.number||'');setPosition(p?.position||'');setPlayerModal(true);}
 async function record(result:Event['result'],which=action){if(!m||!athlete||m.finished||busy) return;const event:Event={id:uid(),player:athlete.id,action:which,result,time:new Date().toISOString(),period:m.period};if(await update({...m,events:[...m.events,event]}))setNotice(`${athlete.name.split(' ')[0]} · ${which} · ${result==='success'?'acerto':result==='error'?'erro':'registrado'}`);}
 function move(id:string,x:number,y:number){setData(d=>({...d,matches:d.matches.map(a=>a.id===m?.id?{...a,players:a.players.map(p=>p.id===id?{...p,x,y}:p)}:a)}));}
 async function storePositions(){const latest=dataRef.current.matches.find(x=>x.id===m?.id);if(latest)await update(latest);}
 function reportLines(p?:Player){if(!m)return [];const list=p?events.filter(e=>e.player===p.id):events;const ok=list.filter(e=>e.result==='success').length,err=list.filter(e=>e.result==='error').length;const lines=[p?`ATLETA: ${p.name} | Camisa ${p.number} | ${p.position}`:`EQUIPE: ${m.team}`,`${spec.name} | ${m.team} x ${m.opponent}`,`Data: ${new Date(m.date).toLocaleDateString('pt-BR')} | ${m.finished?'Encerrada':'Em andamento'}`,`Placar informado: ${m.score[0]} x ${m.score[1]}`,'',`Acertos: ${ok} | Erros: ${err} | Aproveitamento: ${pct(ok,ok+err)}%`,`Total de acoes registradas: ${list.length}`,'','DESEMPENHO POR FUNDAMENTO'];for(const a of [...spec.actions,...spec.neutral]){const ev=list.filter(e=>e.action===a);const good=ev.filter(e=>e.result==='success').length,bad=ev.filter(e=>e.result==='error').length;lines.push(spec.neutral.includes(a)?`${a}: ${ev.length}`:`${a}: ${good} acertos | ${bad} erros | ${pct(good,good+bad)}%`);}if(!p){lines.push('','RESUMO POR ATLETA');for(const player of m.players){const es=events.filter(e=>e.player===player.id);lines.push(`${player.number} - ${player.name}: ${es.filter(e=>e.result==='success').length} acertos, ${es.filter(e=>e.result==='error').length} erros`);}}lines.push('','LEITURA PARA O TREINO','Acertos e erros refletem apenas as acoes registradas pelo tecnico.','Use os fundamentos com mais erros para orientar o proximo treino.','Aproveitamento = acertos / (acertos + erros).','Acoes de contagem nao entram no aproveitamento.');return lines;}
 function exportPDF(p?:Player){if(!m)return;download(makePDF(reportLines(p)),`Quadra-${p?.name||m.team}.pdf`);setNotice('PDF gerado. Pronto para compartilhar.');}
 async function share(p?:Player){if(!m)return;const blob=makePDF(reportLines(p));const file=new File([blob],`Quadra-${p?.name||m.team}.pdf`,{type:'application/pdf'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:`Relatório · ${p?.name||m.team}`});}else{exportPDF(p);setNotice('PDF baixado. Anexe no WhatsApp ou envie para o atleta.');}}catch(e){if((e as Error).name!=='AbortError')setNotice('Não foi possível compartilhar. Use Baixar PDF.');}}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'read_team_statistics',title:'Consultar estatísticas da equipe',description:'Consulta os resultados da partida selecionada, sem alterar os registros.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Entrada inválida');const match=dataRef.current.matches.find(x=>x.id===selectedMatch)||dataRef.current.matches[0];return match?{team:match.team,sport:match.sport,events:match.events.length,players:match.players.map(p=>({name:p.name,success:match.events.filter(e=>e.player===p.id&&e.result==='success').length,errors:match.events.filter(e=>e.player===p.id&&e.result==='error').length}))}:{message:'Nenhuma partida cadastrada'};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[selectedMatch]);
 const rows=m?.players.map(p=>{const ev=events.filter(e=>e.player===p.id),ok=ev.filter(e=>e.result==='success').length,bad=ev.filter(e=>e.result==='error').length;return {p,ok,bad,rate:pct(ok,ok+bad)};})||[];
 const rankedErrors=[...rows].filter(x=>x.bad>0).sort((a,b)=>b.bad-a.bad);const best=[...rows].filter(x=>x.ok>0).sort((a,b)=>b.ok-a.ok);const reportP=m?.players.find(p=>p.id===reportPlayer);
 return <div className="app-shell"><header className="header"><a className="brand" href="./" aria-label="Quadra início"><span className="brand-mark"><Grip size={24}/></span>quadra<span className="brand-dot">.</span><small>COACH WORKSPACE</small></a><span className="header-message">O jogo acontece. Você enxerga além.</span><div className="header-right"><span className="save-state">{loading?'Carregando…':busy?'Salvando…':error?'Atenção ao salvamento':revision?'Dados salvos':'Pronto para começar'}</span><span className="avatar">TC</span></div></header>
 <main><div className="topline"><div><span className="eyebrow">SUA EQUIPE. CADA JOGADA.</span><h1>{m?'Visão de jogo':'Sua próxima vitória começa aqui.'}</h1><p>Você cuida do time. A Quadra ajuda a entender o desempenho.</p></div><button className="primary" onClick={()=>{setSetup(true);setTeam('');setOpponent('');}} disabled={loading||busy}><Plus size={18}/> Nova partida</button></div>
 {error&&<div className="error" role="alert">{error} <button onClick={()=>location.reload()}>Recarregar</button></div>}{notice&&<div className="toast" role="status" onClick={()=>setNotice('')}>{notice}<X size={15}/></div>}
 {loading?<div className="empty"><Loader2 className="spin"/><h2>Preparando sua prancheta…</h2></div>:!m?<div className="start-grid"><section className="start-card"><span className="eyebrow">01 / ESCOLHA A MODALIDADE</span><h2>Uma prancheta.<br/>Todo o seu time.</h2><p>Do primeiro saque ao último ponto: registre jogadas, encontre padrões e compartilhe a evolução de cada atleta.</p><div className="sport-cards">{(Object.keys(sports) as Sport[]).map(s=><button key={s} onClick={()=>setSport(s)} className={sport===s?'chosen':''}><Target size={28}/><strong>{sports[s].name}</strong><span>{sports[s].count} em quadra{ s==='futebol'?' / campo':''}</span>{sport===s&&<Check size={17}/>}</button>)}</div><button className="primary" onClick={()=>setSetup(true)}><Plus size={18}/> Criar minha primeira partida</button><small>Cadastre sua equipe e comece com dados reais.</small></section><section className="intro-court"><div className="intro-badge"><ClipboardList size={17}/> SUA PRANCHETA DIGITAL</div><Court sport={sport} players={[]} selected="" onSelect={()=>{}} onMove={()=>{}} drawing={false}/><div className="intro-caption"><h3>Menos anotações.<br/>Mais atenção ao jogo.</h3><p>Toque no atleta, escolha a jogada e registre o resultado. Simples assim.</p></div></section></div>:<>
 <div className="matchbar"><div className="match-identity"><span className="sport-badge">{spec.name}</span><Picker value={m.id} onChange={switchMatch} label="Partida" options={data.matches.map(x=>({value:x.id,label:`${x.team} × ${x.opponent}`}))}/><span className={'match-status '+(m.finished?'closed':'')}>{m.finished?'Encerrada':'Em andamento'}</span></div><div className="score"><button aria-label="Diminuir placar da equipe" disabled={busy||m.finished||m.score[0]===0} onClick={()=>update({...m,score:[Math.max(0,m.score[0]-1),m.score[1]]})}>−</button><button aria-label="Adicionar ponto à equipe" disabled={busy||m.finished} onClick={()=>update({...m,score:[m.score[0]+1,m.score[1]]})}>{m.score[0]}</button><span>:</span><button aria-label="Adicionar ponto ao adversário" disabled={busy||m.finished} onClick={()=>update({...m,score:[m.score[0],m.score[1]+1]})}>{m.score[1]}</button><button aria-label="Diminuir placar do adversário" disabled={busy||m.finished||m.score[1]===0} onClick={()=>update({...m,score:[m.score[0],Math.max(0,m.score[1]-1)]})}>−</button><small>Placar manual</small></div><Picker value={m.period} label={spec.period} onChange={s=>update({...m,period:s})} options={Array.from({length:m.sport==='futebol'?2:m.sport==='basquete'?4:5},(_,i)=>({value:String(i+1),label:`${i+1}º ${spec.period.toLowerCase()}`}))}/></div>
 <div className="metrics"><div><span>Ações registradas</span><strong>{events.length}<Activity/></strong><small>Todos os fundamentos</small></div><div><span>Acertos</span><strong>{success}<Check className="good"/></strong><small>Execuções bem-sucedidas</small></div><div><span>Erros</span><strong>{errors}<X className="bad"/></strong><small>Oportunidades de evolução</small></div><div className="rate-card"><span>Aproveitamento</span><strong>{pct(success,total)}%<Target/></strong><small>{total?'Acertos / tentativas avaliadas':'Registre jogadas para analisar'}</small></div></div>
 <div className="work-nav"><Tabs value={tab} onValueChange={setTab}><TabsList className="workspace-tabs" variant="line"><TabsTrigger value="prancheta"><ClipboardList/>Prancheta</TabsTrigger><TabsTrigger value="estatisticas"><BarChart3/>Estatísticas</TabsTrigger><TabsTrigger value="relatorios"><Download/>Relatórios</TabsTrigger></TabsList></Tabs><span>{new Date(m.date).toLocaleDateString('pt-BR')} · {m.players.length} atletas</span></div>
 {tab==='prancheta'&&<div className="workspace"><aside className="panel roster"><div className="panel-heading"><h2>Seu elenco <small>{m.players.length}</small></h2><button className="icon-button" aria-label="Cadastrar atleta" onClick={()=>openPlayer()} disabled={busy}><Plus size={20}/></button></div><p className="muted">Selecione quem fez a jogada.</p><div className="roster-list">{!m.players.length?<div className="roster-empty"><Users/><p>O jogo começa pelo time.</p><button onClick={()=>openPlayer()}>Cadastrar primeiro atleta</button></div>:m.players.map(p=><div className={'roster-row '+(selected===p.id?'selected':'')} key={p.id}><button className="roster-person" onClick={()=>setSelected(p.id)}><span className="jersey">{p.number}</span><span><strong>{p.name}</strong><small>{p.position||'Atleta'} · {p.active?'Em jogo':'Reserva'}</small></span></button><button className="edit-player" aria-label={'Editar '+p.name} onClick={()=>openPlayer(p)}>•••</button></div>)}</div><div className="roster-foot"><span><span className="line-dot"/> {m.players.filter(p=>p.active).length} em jogo</span><button onClick={()=>openPlayer()} disabled={busy}>Adicionar atleta</button></div></aside>
 <section className="panel board"><div className="panel-heading"><div><h2>Prancheta tática</h2><p className="muted">O posicionamento do seu time, do seu jeito.</p></div><button className={'outline '+(drawing?'active':'')} onClick={()=>setDrawing(!drawing)}>{drawing?'Selecionar atletas':'Desenhar jogada'}</button></div><div onPointerUp={storePositions}><Court key={m.id} sport={m.sport} players={m.players} selected={selected} onSelect={setSelected} onMove={move} drawing={drawing}/></div><div className="board-bottom"><span>Posições livres · desenhos temporários</span>{athlete&&<button className="outline" disabled={busy||(!athlete.active&&m.players.filter(p=>p.active).length>=spec.count)} onClick={()=>update({...m,players:m.players.map(p=>p.id===athlete.id?{...p,active:!p.active}:p)})}>{athlete.active?'Mover para reserva':'Colocar em jogo'}</button>}</div></section>
 <aside className="panel recorder"><span className="eyebrow">REGISTRO RÁPIDO</span><h2>Uma jogada. Um toque.</h2><div className="selected-athlete"><span className="jersey big">{athlete?.number||'–'}</span><div><small>ATLETA SELECIONADO</small><strong>{athlete?.name||'Escolha um atleta'}</strong><span>{athlete?.position||'Selecione na prancheta ou elenco'}</span></div></div><label className="field-label">Fundamento</label><div className="action-grid">{spec.actions.map(a=><button key={a} className={action===a?'active':''} onClick={()=>setAction(a)}>{a}</button>)}</div><div className="result-buttons"><button className="success-btn" disabled={!athlete||busy||m.finished} onClick={()=>record('success')}><Check/>Acertou</button><button className="error-btn" disabled={!athlete||busy||m.finished} onClick={()=>record('error')}><X/>Errou</button></div>{spec.neutral.length>0&&<><label className="field-label">Outras ações · contagem</label><div className="neutral-actions">{spec.neutral.map(a=><button disabled={!athlete||busy||m.finished} key={a} onClick={()=>record('neutral',a)}><Plus size={13}/>{a}</button>)}</div></>}<button className="undo" disabled={!events.length||busy||m.finished} onClick={()=>update({...m,events:events.slice(0,-1)})}><Undo2 size={16}/> Desfazer última jogada</button><p className="recorder-tip">Registre apenas o que você observou. A estatística fica mais útil a cada jogada.</p></aside>
 <section className="panel timeline"><div className="panel-heading"><h2>Últimas jogadas</h2><small>{events.length} registros</small></div>{!events.length?<p className="muted">A primeira jogada registrada aparecerá aqui.</p>:events.slice(-7).reverse().map(e=><div className="event-row" key={e.id}><span className={'result-icon '+e.result}>{e.result==='success'?<Check size={15}/>:e.result==='error'?<X size={15}/>:<Plus size={15}/>}</span><strong>{m.players.find(p=>p.id===e.player)?.name||'Atleta'}</strong><span>{e.action}</span><span>{e.result==='success'?'Acerto':e.result==='error'?'Erro':'Contagem'}</span><small>{e.period}º {spec.period.toLowerCase()} · {new Date(e.time).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></div>)}</section></div>}
 {tab==='estatisticas'&&<div className="stats-grid"><section className="panel fundamentals"><div className="panel-heading"><h2>O que o jogo está dizendo</h2><span className="legend"><i/> Acertos <i className="red"/> Erros</span></div>{spec.actions.map(a=>{const ev=events.filter(e=>e.action===a),ok=ev.filter(e=>e.result==='success').length,bad=ev.filter(e=>e.result==='error').length;return <div className="fundamental" key={a}><div><strong>{a}</strong><span>{ok} acertos · {bad} erros <b>{pct(ok,ok+bad)}%</b></span></div><div className="bar-track"><i style={{width:`${pct(ok,ok+bad)}%`}}/><i className="red" style={{width:`${pct(bad,ok+bad)}%`}}/></div></div>;})}{spec.neutral.length>0&&<div className="neutral-summary">{spec.neutral.map(a=><div key={a}><span>{a}</span><strong>{events.filter(e=>e.action===a).length}</strong></div>)}</div>}<p className="muted">Aproveitamento considera apenas ações marcadas como acerto ou erro.</p></section><section className="panel insights"><span className="eyebrow">DO DADO AO TREINO</span><h2>Um olhar para evoluir.</h2><div className="insight"><Target/><div><small>MAIS ACERTOS</small><strong>{best[0]?.p.name||'Aguardando jogadas'}</strong><p>{best[0]?`${best[0].ok} acertos registrados`:'Registre ações para identificar destaques.'}</p></div></div><div className="insight"><RotateCw/><div><small>ATENÇÃO NO PRÓXIMO TREINO</small><strong>{rankedErrors[0]?.p.name||'Nenhum erro registrado'}</strong><p>{rankedErrors[0]?`${rankedErrors[0].bad} erros registrados`:'Acompanhe os fundamentos ao longo do jogo.'}</p></div></div><h3>Mais erros por fundamento</h3>{spec.actions.map(a=>{const ranked=m.players.map(p=>({p,n:events.filter(e=>e.player===p.id&&e.action===a&&e.result==='error').length})).filter(x=>x.n).sort((x,y)=>y.n-x.n);const tied=ranked.filter(x=>x.n===ranked[0]?.n);return <div className="rank-line" key={a}><span>{a}</span><strong>{tied.length?tied.map(x=>x.p.name.split(' ')[0]).join(', '):'—'}</strong><b>{ranked[0]?.n||0}</b></div>;})}<p className="muted">Empates são exibidos juntos. Os números ajudam a orientar, não a rotular atletas.</p></section><section className="panel table-panel"><h2>Desempenho individual</h2><div className="table-scroll"><table><thead><tr><th>Atleta</th><th>Acertos</th><th>Erros</th><th>Aproveitamento</th><th>Relatório</th></tr></thead><tbody>{rows.map(x=><tr key={x.p.id}><td><span className="number-tag">{x.p.number}</span>{x.p.name}</td><td className="good">{x.ok}</td><td className="bad">{x.bad}</td><td>{x.rate}%</td><td><button onClick={()=>exportPDF(x.p)}><Download size={16}/> PDF</button></td></tr>)}</tbody></table>{!rows.length&&<p className="muted">Cadastre atletas para acompanhar o desempenho individual.</p>}</div></section></div>}
 {tab==='relatorios'&&<div className="reports-grid"><section className="panel report-config"><span className="eyebrow">COMPARTILHE A EVOLUÇÃO</span><h2>Cada atleta merece<br/>um retorno claro.</h2><p>Transforme as jogadas registradas em um relatório com acertos, erros e aproveitamento por fundamento.</p><label className="field-label">Gerar relatório de</label><Picker value={reportPlayer} onChange={setReportPlayer} label="Atleta ou equipe" options={[{value:'team',label:'Equipe completa'},...m.players.map(p=>({value:p.id,label:`${p.number} · ${p.name}`}))]}/><button className="primary" onClick={()=>exportPDF(reportP)}><Download size={18}/> Baixar PDF</button><button className="outline" onClick={()=>share(reportP)}><Share2 size={18}/> Compartilhar relatório</button><small>Quando o compartilhamento direto não estiver disponível, baixe o PDF e anexe na sua conversa.</small><div className="end-match"><h3>{m.finished?'Partida encerrada':'Finalizou o jogo?'}</h3><p>Os relatórios ficam disponíveis no histórico de partidas.</p><button className="outline" disabled={busy} onClick={()=>update({...m,finished:!m.finished})}><Flag size={16}/>{m.finished?'Reabrir registros':'Encerrar partida'}</button></div></section><section className="report-preview"><div className="paper-top"><strong>quadra.</strong><span>RELATÓRIO DE DESEMPENHO</span></div><span className="eyebrow">{spec.name.toUpperCase()} / {new Date(m.date).toLocaleDateString('pt-BR')}</span><h2>{reportP?.name||m.team}</h2><p>{m.team} × {m.opponent}{reportP?` · Camisa ${reportP.number}`:''}</p><div className="paper-stats">{(()=>{const ev=reportP?events.filter(e=>e.player===reportP.id):events,ok=ev.filter(e=>e.result==='success').length,bad=ev.filter(e=>e.result==='error').length;return <><div><strong>{ok}</strong><span>Acertos</span></div><div><strong>{bad}</strong><span>Erros</span></div><div><strong>{pct(ok,ok+bad)}%</strong><span>Aproveitamento</span></div></>;})()}</div><h3>Fundamento por fundamento</h3>{spec.actions.map(a=>{const ev=events.filter(e=>e.action===a&&(!reportP||e.player===reportP.id));return <div className="paper-row" key={a}><strong>{a}</strong><span>{ev.filter(e=>e.result==='success').length} acertos</span><span>{ev.filter(e=>e.result==='error').length} erros</span></div>;})}<div className="paper-note"><strong>O próximo treino começa com esse olhar.</strong><p>Reconheça os acertos. Trabalhe os fundamentos que precisam de atenção. Evolua junto com o seu time.</p></div><small>Prévia do conteúdo · PDF com todos os fundamentos e critérios de cálculo.</small></section></div>}
 </>}
 <footer><span>quadra. <small>Clareza para decidir. Dados para evoluir.</small></span><small>Feito para quem vive o jogo.</small></footer></main>
 <Dialog open={setup} onOpenChange={setSetup}><DialogContent className="modal"><DialogHeader><DialogTitle>Prepare sua partida</DialogTitle><DialogDescription>Escolha a modalidade e dê um nome à sua equipe.</DialogDescription></DialogHeader><form onSubmit={create}><label>Modalidade</label><Picker value={sport} onChange={s=>setSport(s as Sport)} label="Modalidade" options={(Object.keys(sports) as Sport[]).map(s=>({value:s,label:sports[s].name}))}/><label htmlFor="team">Sua equipe</label><input id="team" required maxLength={60} placeholder="Ex.: Vôlei Suzano feminino" value={team} onChange={e=>setTeam(e.target.value)}/><label htmlFor="opponent">Adversário ou treino</label><input id="opponent" maxLength={60} placeholder="Ex.: Equipe visitante ou Treino de terça" value={opponent} onChange={e=>setOpponent(e.target.value)}/><button className="primary" type="submit" disabled={busy||!team.trim()}>{busy?'Salvando…':'Criar partida'}</button></form></DialogContent></Dialog>
 <Dialog open={playerModal} onOpenChange={setPlayerModal}><DialogContent className="modal"><DialogHeader><DialogTitle>{editId?'Editar atleta':'Adicionar atleta'}</DialogTitle><DialogDescription>Nome e número ajudam a registrar a pessoa certa.</DialogDescription></DialogHeader><form onSubmit={addPlayer}><label htmlFor="name">Nome do atleta</label><input id="name" required maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Julia Santos"/><div className="form-split"><div><label htmlFor="number">Número</label><input id="number" required inputMode="numeric" pattern="[0-9]{1,3}" maxLength={3} value={number} onChange={e=>setNumber(e.target.value)} placeholder="10"/></div><div><label htmlFor="position">Posição</label><input id="position" maxLength={40} value={position} onChange={e=>setPosition(e.target.value)} placeholder="Ex.: Ponteira"/></div></div><button className="primary" disabled={busy||!name.trim()} type="submit">{busy?'Salvando…':'Salvar atleta'}</button></form></DialogContent></Dialog>
 </div>;
}
