const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n),num=n=>n.toLocaleString('pt-BR');
const contacts={carlos:{name:'Carlos',phone:'5511994388682'},ney:{name:'Ney',phone:'5511989795659'}};
const wa=(message,recipient='carlos')=>'https://wa.me/'+contacts[recipient].phone+'?text='+encodeURIComponent(message);
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let vehicles=[],type='',limit=9,current=null,photo=0;
function wireWhatsApp(){ $$('.wa').forEach(a=>{a.href=wa(a.dataset.message);a.target='_blank';a.rel='noopener';});}wireWhatsApp();
const image=id=>'images/'+id+'.webp';
const vehicleMessage=(v,financing=true)=>`Olá! Vi no site da Neycar o ${v.brand} ${v.model} ${v.version}, ano ${v.production}/${v.year}, anunciado por ${money(v.price)}. ${financing?'Gostaria de simular um financiamento. Quais são as opções de entrada e parcelas?':'Gostaria de saber mais e confirmar a disponibilidade.'}`;
function filtered(){const q=$('#query').value.trim().toLocaleLowerCase('pt-BR');let list=vehicles.filter(v=>(!type||v.type===type)&&(!q||`${v.brand} ${v.model} ${v.version}`.toLocaleLowerCase('pt-BR').includes(q))&&(!$('#brand').value||v.brand===$('#brand').value)&&(!$('#min').value||v.price>=Number($('#min').value))&&(!$('#max').value||v.price<=Number($('#max').value))&&(!$('#yearMin').value||v.year>=Number($('#yearMin').value))&&(!$('#yearMax').value||v.year<=Number($('#yearMax').value))&&(!$('#transmission').value||v.transmission===$('#transmission').value));const mode=$('#sort').value;const sorts={cheap:(a,b)=>a.price-b.price,expensive:(a,b)=>b.price-a.price,new:(a,b)=>b.year-a.year,old:(a,b)=>a.year-b.year};if(sorts[mode])list.sort(sorts[mode]);return list;}
function render(){const list=filtered();$('#count').textContent=`${list.length} ${list.length===1?'veículo encontrado':'veículos encontrados'}`;$('#grid').innerHTML=list.slice(0,limit).map(v=>`<article class="card"><button class="card-image" data-open="${v.id}" aria-label="Ver fotos de ${escapeHtml(v.brand+' '+v.model)}"><img src="${image(v.images[0])}" alt="${escapeHtml(v.brand+' '+v.model+' '+v.year)} anunciado pela Neycar" loading="lazy"><span class="photo-count">▧ ${v.images.length} fotos</span></button><div class="card-body"><p class="card-brand">${escapeHtml(v.brand)}</p><h3>${escapeHtml(v.model)}</h3><p class="version">${escapeHtml(v.version)}</p><div class="specs"><span>${v.production}/${v.year}</span><span>${num(v.km)} km</span><span>${escapeHtml(v.transmission)}</span></div><strong class="price">${money(v.price)}</strong><a class="button" href="${wa(vehicleMessage(v))}" target="_blank" rel="noopener">Simular financiamento ↗</a><button class="details-link" data-open="${v.id}">Ver fotos e detalhes</button></div></article>`).join('');$('#empty').hidden=list.length>0;$('#empty h3').textContent=type==='Moto'?'Procurando uma moto?':'Nenhum veículo por aqui.';$('#empty p').textContent=type==='Moto'?'Consulte a equipe para receber as motos disponíveis, fotos e valores pelo WhatsApp.':'Experimente outros filtros ou conte para a gente o que procura.';$('#more').hidden=list.length<=limit;}
function reset(){type='';limit=9;['query','brand','min','max','yearMin','yearMax','transmission'].forEach(id=>$('#'+id).value='');$('#sort').value='featured';updateTabs();render();}
function updateTabs(){$$('[data-type]').forEach(b=>{b.classList.toggle('active',b.dataset.type===type);b.setAttribute('aria-pressed',String(b.dataset.type===type));});}
$$('.filters input,.filters select,#sort').forEach(el=>el.addEventListener('input',()=>{limit=9;render();}));$$('[data-type]').forEach(b=>b.addEventListener('click',()=>{type=b.dataset.type;limit=9;updateTabs();render();}));$('#clear').onclick=reset;$('#reset-empty').onclick=reset;$('#more').onclick=()=>{limit+=9;render();};
function gallery(){if(!current)return;$('#gallery-image').src=image(current.images[photo]);$('#gallery-image').alt=`${current.brand} ${current.model} — foto ${photo+1} de ${current.images.length}`;$('#photo-position').textContent=`${photo+1} / ${current.images.length}`;$$('[data-photo]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.photo)===photo);b.setAttribute('aria-pressed',String(Number(b.dataset.photo)===photo));});}
function openVehicle(id){const v=vehicles.find(v=>v.id===Number(id));if(!v)return;current=v;photo=0;$('#detail-content').innerHTML=`<div class="detail-layout"><div class="gallery"><div class="gallery-main"><img id="gallery-image" src="${image(v.images[0])}" alt="${escapeHtml(v.model)}"></div><div class="gallery-nav"><button id="previous" aria-label="Foto anterior">←</button><span id="photo-position"></span><button id="next" aria-label="Próxima foto">→</button></div><div class="thumbs">${v.images.map((id,i)=>`<button data-photo="${i}" aria-label="Abrir foto ${i+1}"><img src="${image(id)}" alt="Foto ${i+1}" loading="lazy"></button>`).join('')}</div></div><div class="detail-copy"><p class="eyebrow">${escapeHtml(v.brand)} · NEYCAR</p><h2 id="detail-title">${escapeHtml(v.model)}</h2><p>${escapeHtml(v.version)}</p><strong class="price">${money(v.price)}</strong><div class="detail-specs">${[['Ano',v.production+'/'+v.year],['Quilometragem',num(v.km)+' km'],['Câmbio',v.transmission],['Combustível',v.fuel],['Categoria',v.category],['Localização','Suzano, SP']].map(([k,val])=>`<div><span>${k}</span>${escapeHtml(val)}</div>`).join('')}</div><p>Gostou deste ${escapeHtml(v.model)}? Fale com a equipe, tire suas dúvidas e agende uma visita para conhecê-lo de perto.</p><a class="button yellow" href="${wa(vehicleMessage(v))}" target="_blank" rel="noopener">Simular financiamento ↗</a><a class="button outline" href="${wa(vehicleMessage(v,false))}" target="_blank" rel="noopener">Tenho interesse neste veículo</a><small>Fotos e informações do anúncio da loja. Confirme preço, disponibilidade e especificações com o vendedor.</small></div></div>`;$('#previous').onclick=()=>{photo=(photo-1+v.images.length)%v.images.length;gallery();};$('#next').onclick=()=>{photo=(photo+1)%v.images.length;gallery();};$$('[data-photo]').forEach(b=>b.onclick=()=>{photo=Number(b.dataset.photo);gallery();});gallery();if(!$('#detail').open)$('#detail').showModal();document.body.style.overflow='hidden';}
document.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openVehicle(b.dataset.open);});$('.close').onclick=()=>$('#detail').close();$('#detail').addEventListener('close',()=>{document.body.style.overflow=$('#contact-choice').open?'hidden':'';});$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});$('#detail').addEventListener('keydown',e=>{if(e.key==='ArrowRight')$('#next').click();if(e.key==='ArrowLeft')$('#previous').click();});
fetch('vehicles.json').then(r=>{if(!r.ok)throw Error('Estoque indisponível');return r.json();}).then(data=>{vehicles=data;$('#brand').innerHTML+=[...new Set(vehicles.map(v=>v.brand))].sort().map(b=>`<option>${escapeHtml(b)}</option>`).join('');render();const context=document.modelContext;if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'filter_neycar_inventory',description:'Filtra o estoque visível da Neycar por texto e preço máximo, e retorna os veículos encontrados. Não envia mensagens.',inputSchema:{type:'object',properties:{query:{type:'string'},maxPrice:{type:'number',minimum:0}},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||(input.query!==undefined&&typeof input.query!=='string')||(input.maxPrice!==undefined&&(typeof input.maxPrice!=='number'||!Number.isFinite(input.maxPrice)||input.maxPrice<0)))throw Error('Filtros inválidos');reset();$('#query').value=input.query||'';$('#max').value=input.maxPrice??'';render();return filtered().map(v=>({id:v.id,vehicle:v.brand+' '+v.model,year:v.year,price:v.price}));}})).catch(()=>{});}catch{}}}).catch(()=>{$('#count').textContent='Não foi possível carregar o estoque.';$('#grid').innerHTML='<p>Atualize a página ou <a href="'+wa('Olá! Gostaria de consultar o estoque da Neycar.')+'">consulte os veículos pelo WhatsApp</a>.</p>';$('#more').hidden=true;});

function chooseContact(message){for(const [key,contact] of Object.entries(contacts))$('#choose-'+key).href=wa(message.replace(/^Olá!/, 'Olá, '+contact.name+'!'),key);if(!$('#contact-choice').open)$('#contact-choice').showModal();document.body.style.overflow='hidden';}
document.addEventListener('click',event=>{const link=event.target.closest('a');if(!link||link.dataset.contact||!link.href.startsWith('https://wa.me/'))return;event.preventDefault();const message=new URL(link.href).searchParams.get('text')||'Olá! Gostaria de atendimento na Neycar.';chooseContact(message);});
$('.contact-close').onclick=()=>$('#contact-choice').close();$('#contact-choice').addEventListener('close',()=>{document.body.style.overflow=$('#detail').open?'hidden':'';});
$('#contact-choice').addEventListener('click',event=>{if(event.target!==$('#contact-choice'))return;const r=event.target.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)event.target.close();});
const motion=window.matchMedia('(prefers-reduced-motion: reduce)');const finePointer=window.matchMedia('(hover: hover) and (pointer: fine)');const showcase=$('.hero-showcase');if(showcase&&finePointer.matches&&!motion.matches){showcase.addEventListener('pointermove',event=>{const r=showcase.getBoundingClientRect();showcase.style.setProperty('--tilt-x',((event.clientY-r.top)/r.height-.5)*-5+'deg');showcase.style.setProperty('--tilt-y',((event.clientX-r.left)/r.width-.5)*6+'deg');});showcase.addEventListener('pointerleave',()=>{showcase.style.setProperty('--tilt-x','0deg');showcase.style.setProperty('--tilt-y','0deg');});}
