"use client";
import {useEffect,useRef,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Toaster,toast} from 'sonner';
import {ShieldCheck,BookOpen,CalendarDays,Check,Play,Pause,RotateCcw,Target,Brain,ChevronLeft,ChevronRight,ExternalLink,Clock,Trophy,Volleyball,CheckCircle2} from 'lucide-react';
import {aulas,Aula,bank,dailyQuestions,mock,checklist,sources,official} from '@/lib/maua';
import {Question} from '@/lib/curriculum';
type Data=Record<string,any>;
const date=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const key=(d:number,s='complete')=>'task-maua-oct-'+d+'-'+s;
const out=(url:string,label:string,cls='source-link')=><a className={cls} href={url} target="_blank" rel="noreferrer">{label}<ExternalLink size={15}/></a>;
function Quiz({items,mode,onSave,ready}:{items:Question[];mode:string;onSave:(v:any)=>Promise<boolean>;ready:boolean}){
 const [answers,setAnswers]=useState<Record<string,number>>({}),[graded,setGraded]=useState(false),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false);
 const record=useRef<any>(null),weighted=mode==='Simulado';
 const all=items.length>0&&items.every(q=>answers[q.id]!==undefined),weight=(q:Question)=>weighted&&q.area==='Legislação'?4:1;
 const points=items.reduce((s,q)=>s+(answers[q.id]===q.correct?weight(q):0),0),max=items.reduce((s,q)=>s+weight(q),0);
 async function finish(){if(!all)return;setGraded(true);if(!record.current)record.current={id:crypto.randomUUID(),at:new Date().toISOString(),mode,answers,correct:items.filter(q=>answers[q.id]===q.correct).length,total:items.length,points,max};setSaving(true);setSaved(await onSave(record.current));setSaving(false)}
 if(!items.length)return <p>Nenhum erro registrado neste plano. Comece pelas questões da aula.</p>;
 return <div className="quiz"><div className="section-heading"><div><span className="eyebrow">{mode} • questões autorais</span><h2>{graded?'Confira o raciocínio':'Agora é com você'}</h2></div><span className="pill">{Object.keys(answers).length}/{items.length}</span></div><p>Responda sem consultar. A correção aparece ao finalizar o bloco.</p>
 {items.map((q,i)=><fieldset key={q.id} className={'question '+(graded?(answers[q.id]===q.correct?'right':'wrong'):'')}><legend><span>{String(i+1).padStart(2,'0')}</span> {q.q}</legend><RadioGroup disabled={graded} value={answers[q.id]===undefined?'':String(answers[q.id])} onValueChange={v=>{if(!graded)setAnswers(s=>({...s,[q.id]:Number(v)}))}}>{q.options.map((option,j)=><label key={j} className={'option '+(graded&&j===q.correct?'correct-option':'')}><RadioGroupItem value={String(j)} id={q.id+'-'+j}/><span><b>{String.fromCharCode(65+j)}.</b> {option}</span>{graded&&j===q.correct&&<Check size={18}/>}</label>)}</RadioGroup>{graded&&<div className="explanation"><b>{answers[q.id]===q.correct?'Acertou.':'Vamos ajustar.'}</b> {q.why}</div>}</fieldset>)}
 {graded&&<div className="result" role="status"><Trophy/><div><strong>{points}/{max} {weighted?'pontos':'acertos'}</strong><p>{weighted?'Meta pessoal de treino: 80/100. Não é nota de corte nem garantia de aprovação.':'Leia a explicação, mesmo quando acertar. Tente explicar uma situação diferente.'}</p><small>{saved?'Resultado salvo.':'Resultado ainda não salvo.'}</small></div></div>}
 <button className="primary full" onClick={finish} disabled={!all||saving||!ready||(graded&&saved)}>{saving?'Salvando…':graded?(saved?'Resultado salvo':'Tentar salvar resultado'):'Corrigir minhas respostas'}</button></div>
}
export default function Home(){
 const [data,setData]=useState<Data>({}),[ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [day,setDay]=useState(1),[tab,setTab]=useState('aula'),[notes,setNotes]=useState(''),[answer,setAnswer]=useState(false),[today,setToday]=useState('2026-10-05');
 const [seconds,setSeconds]=useState(900),[running,setRunning]=useState(false),[end,setEnd]=useState(0);
 const [practice,setPractice]=useState<Question[]>([]),[mode,setMode]=useState('Treino'),[quizVersion,setQuizVersion]=useState(0);
 const [taf,setTaf]=useState({run:'',sprint:'',push:'',abs:''});
 const init=useRef(false),stateRef=useRef(data);stateRef.current=data;
 const lesson=aulas[day-1],done=aulas.filter(a=>data[key(a.day)]),progress=Math.round(done.length/aulas.length*100);
 const attempts=Object.entries(data).filter(([k,v])=>k.startsWith('attempt-maua-oct-')&&v).map(([,v])=>v).sort((a,b)=>a.at.localeCompare(b.at));
 const lastAnswers:Record<string,number>={};attempts.forEach(a=>Object.assign(lastAnswers,a.answers));const wrong=bank.filter(q=>lastAnswers[q.id]!==undefined&&lastAnswers[q.id]!==q.correct);
 const daysLeft=Math.max(0,Math.round((new Date('2026-11-01T12:00:00-03:00').getTime()-new Date(today+'T12:00:00-03:00').getTime())/86400000));
 const reviews=done.filter(a=>{const r=data['review-maua-oct-'+a.day],when=r?.at||data[key(a.day)].at,interval=r?.failed?1:[1,3,7,14][Math.min(r?.count||0,3)];return new Date(when).getTime()+interval*86400000<=Date.now()});
 async function load(){setError('');try{const r=await fetch('/api/progress',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json() as Data;setData(d);setReady(true);if(!init.current){setDay(aulas.find(a=>!d[key(a.day)])?.day||aulas.length);setTaf(d['taf-maua-oct']||{run:'',sprint:'',push:'',abs:''});init.current=true}}catch{setReady(false);setError('Não consegui carregar seu progresso. Você pode ler as aulas; tente reconectar antes de salvar.');}}
 useEffect(()=>{setToday(date());load()},[]);
 useEffect(()=>{setNotes(data['note-maua-oct-'+day]||'');setAnswer(false)},[day,ready]);
 useEffect(()=>{if(!running)return;const timer=setInterval(()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));setSeconds(left);if(!left){setRunning(false);toast.success('Bloco encerrado. Faça uma pausa curta.')}},300);return()=>clearInterval(timer)},[running,end]);
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const controller=new AbortController();try{mc.registerTool({name:'read_study_progress',description:'Lê o progresso do plano de outubro para GCM Mauá. Não altera registros.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async(input:any)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Use objeto vazio');return{content:[{type:'text',text:JSON.stringify({completed:aulas.filter(a=>stateRef.current[key(a.day)]).map(a=>({day:a.day,title:a.title})),total:aulas.length})}]}}},{signal:controller.signal})}catch{}return()=>controller.abort()},[]);
 async function save(k:string,value:any){if(!ready)return false;try{const r=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:k,value})});if(!r.ok)throw Error();setData(d=>({...d,[k]:value}));return true}catch{toast.error('Não salvou. O preenchimento continua na tela; tente novamente.');return false}}
 async function check(k:string,on:boolean){setBusy(true);if(await save(k,on?{at:new Date().toISOString()}:null))toast.success(on?'Etapa concluída e salva. Boa!':'Marcação removida.');setBusy(false)}
 function select(n:number){setDay(n);setTab('aula');setAnswer(false);window.scrollTo({top:0,behavior:'smooth'})}
 function start(type:string){setPractice(type==='Erros'?wrong:type==='Simulado'?mock(attempts.length+7):bank.filter(q=>q.area==='Legislação').slice(0,10));setMode(type);setQuizVersion(v=>v+1);setTab('treino')}
 const saveAttempt=(v:any)=>save('attempt-maua-oct-'+v.id,v);
 const steps=[['video','Assisti ao trecho ou fiz a leitura indicada'],['resumo','Li o resumo e tentei explicar sem olhar'],['questoes','Respondi e corrigi as questões']],stepCount=steps.filter(([id])=>data[key(day,id)]).length;
 const mark=(s:number)=><label className="checkline"><Checkbox disabled={!ready||busy} checked={!!data[key(day,steps[s][0])]} onCheckedChange={v=>check(key(day,steps[s][0]),v===true)}/><span>{steps[s][1]}</span></label>;
 async function review(a:Aula,good:boolean){setBusy(true);if(await save('review-maua-oct-'+a.day,{at:new Date().toISOString(),count:(data['review-maua-oct-'+a.day]?.count||0)+(good?1:0),failed:!good}))toast.success(good?'Revisão salva.':'O assunto volta amanhã.');setBusy(false)}
 return <><Toaster richColors position="top-center"/><Tabs value={tab} onValueChange={setTab} className="app">
 <aside className="sidebar"><div className="brand"><span><ShieldCheck size={26}/></span><div>MISSÃO <b>MAUÁ</b><small>GCM · 2026</small></div></div><div className="profile">Seu próximo avanço.<small>Um dia. Uma aula. Um avanço.</small></div><TabsList className="nav"><TabsTrigger value="aula"><BookOpen size={19}/>Minha aula</TabsTrigger><TabsTrigger value="plano"><CalendarDays size={19}/>Plano de outubro</TabsTrigger><TabsTrigger value="treino"><Target size={19}/>Questões e simulados</TabsTrigger><TabsTrigger value="revisao"><Brain size={19}/>Revisar <span className="count">{reviews.length}</span></TabsTrigger><TabsTrigger value="edital"><ShieldCheck size={19}/>Edital e fontes</TabsTrigger></TabsList><div className="side-progress"><div><b>{done.length} de {aulas.length}</b><span>aulas concluídas</span></div><Progress value={progress}/><p>{done.length===0?'Seu primeiro ponto começa hoje.':'Você já saiu do zero. Continue.'}</p><div className="badges"><span className={done.length>=1?'earned':''}>1º ponto</span><span className={done.length>=7?'earned':''}>7 aulas</span><span className={done.length>=20?'earned':''}>20 aulas</span></div></div><div className="side-bottom"><Volleyball size={23}/><span>Constância ganha sets.<small>Recomeço em 05/10.</small></span></div></aside>
 <main><header className="topbar"><span>DEMONSTRAÇÃO DO PORTFÓLIO <b>GCM MAUÁ</b></span><span className="exam">{daysLeft>0?daysLeft+' dias até a data prevista':'Consulte a convocação'} <b>01 NOV</b></span></header>
 {error?<div role="alert" className="notice error">{error}<button onClick={load}>Tentar novamente</button></div>:!ready?<div className="notice" role="status">Carregando seu progresso salvo…</div>:null}
 <div className="workspace"><TabsContent value="aula"><div className="page-intro"><div><span className="eyebrow">OUTUBRO É O SEU RECOMEÇO</span><h1>Vamos ganhar o próximo ponto.</h1><p>Faça só esta aula agora. O restante já está organizado.</p></div><span className="date-tag">{lesson.date.slice(-2)}<small>OUT</small></span></div>
 <div className="lesson-layout"><div className="lesson-main"><section className="lesson-hero"><div className="hero-meta"><span>AULA {String(day).padStart(2,'0')} / {aulas.length}</span><span><Clock size={16}/>{lesson.minutes} min sugeridos</span></div><h2>{lesson.title}</h2><p>{lesson.reading}</p><div className="hero-foot"><span>{lesson.kind==='simulado'?'Hoje é treino com correção':day<=3?'Comece leve: 10 + 10 + 10 minutos':'Pode dividir: almoço + depois da faculdade'}</span>{data[key(day)]&&<span className="completed"><CheckCircle2 size={17}/>Concluída</span>}</div></section>
 <section className="card analogy"><span className="section-number"><Volleyball size={22}/></span><div><span className="eyebrow">PRIMEIRO, ENTENDA COM UM EXEMPLO</span><h3>Da sua rotina para a prova</h3><p>{lesson.analogy}</p></div></section>
 <section className="card"><div className="section-heading"><div><span className="eyebrow">01 · ASSISTIR OU LER</span><h2>{lesson.video?'Seu apoio em vídeo':'Leitura de hoje'}</h2></div><Play size={25}/></div>{lesson.video?<><div className="video-panel"><div className="play-icon"><Play fill="currentColor"/></div><div><h3>{lesson.videoTitle}</h3><p>Use 10–15 minutos no tema indicado. Se for longo, anote onde parou.</p>{out('https://www.youtube.com/watch?v='+lesson.video,'Abrir vídeo no YouTube','primary video-button')}</div></div><small className="muted">Vídeo selecionado pelo tema, sem validação integral da transcrição. Resumos e questões são da matéria. Nas aulas locais, o vídeo é complemento nacional: priorize a leitura de Mauá.</small></>:<p>Hoje, priorize suas anotações e a convocação oficial.</p>}<div className="reading"><b>Leitura:</b> {lesson.reading}{out(lesson.url,'Abrir fonte da aula')}{lesson.moreSources?.map(r=><span key={r.url}>{out(r.url,r.label)}</span>)}</div>{mark(0)}</section>
 <section className="card"><span className="eyebrow">02 · ENTENDER E LEMBRAR</span><h2>A aula, sem complicar</h2><div className="prose">{lesson.parts.map((p,i)=><p key={i}><span className="paragraph-number">{i+1}</span>{p}</p>)}</div><div className="trap"><b>Cuidado com esta troca</b><p>{lesson.trap}</p></div><div className="recall"><Brain size={23}/><div><b>Feche o resumo e responda em voz alta</b><p>{lesson.recall}</p><button className="text-button" onClick={()=>setAnswer(!answer)} aria-expanded={answer}>{answer?'Ocultar resposta':'Conferir depois de tentar'}</button>{answer&&<p className="model-answer">{lesson.answer}</p>}</div></div>{mark(1)}<details><summary>Guardar minha explicação ou dúvida</summary><label htmlFor="notes" className="sr-only">Minha anotação</label><textarea id="notes" value={notes} onChange={e=>setNotes(e.target.value)} maxLength={5000} placeholder="Explique com suas palavras. O que confundiu?"/><button className="secondary" disabled={!ready||busy} onClick={async()=>{setBusy(true);if(await save('note-maua-oct-'+day,notes))toast.success('Anotação salva.');setBusy(false)}}>Salvar anotação</button></details></section>
 <section className="card mini"><span className="eyebrow">MICROTREINO · 5 MINUTOS</span><h3>Um ponto nas matérias básicas</h3><p>{lesson.extra}</p><small>Resolva mentalmente e confira a explicação. Nos simulados, use este tempo para corrigir.</small></section>
 <section className="card"><span className="eyebrow">03 · RESPONDER E CORRIGIR</span><Quiz key={'daily-'+day} items={dailyQuestions(lesson)} mode={lesson.kind==='simulado'?'Simulado':'Aula'} onSave={saveAttempt} ready={ready}/>{mark(2)}</section>
 <section className="finish-card"><span className="eyebrow">04 · REGISTRAR SEU AVANÇO</span><h2>{data[key(day)]?'Aula concluída. Ponto seu!':'Terminou o treino de hoje?'}</h2><p>{stepCount}/3 etapas marcadas. Assistir, explicar e corrigir fazem parte.</p><button className="primary" disabled={!ready||busy||stepCount<3||!!data[key(day)]} onClick={()=>check(key(day),true)}><CheckCircle2 size={20}/>{data[key(day)]?'Conclusão salva':'Concluir esta aula'}</button>{data[key(day)]&&<button className="text-button" disabled={busy} onClick={()=>check(key(day),false)}>Desfazer conclusão</button>}</section><div className="lesson-nav"><button className="secondary" disabled={day===1} onClick={()=>select(day-1)}><ChevronLeft size={18}/>Anterior</button><button className="secondary" disabled={day===aulas.length} onClick={()=>select(day+1)}>Próxima aula<ChevronRight size={18}/></button></div></div>
 <aside className="right-rail"><section className="card timer"><span className="eyebrow">UM BLOCO DE CADA VEZ</span><div className="timer-value">{String(Math.floor(seconds/60)).padStart(2,'0')}<span>:</span>{String(seconds%60).padStart(2,'0')}</div><div className="timer-actions"><button className="primary" onClick={()=>{if(!running)setEnd(Date.now()+seconds*1000);setRunning(!running)}}>{running?<Pause size={17}/>:<Play size={17}/>} {running?'Pausar':'Começar'}</button><button className="icon-button" aria-label="Reiniciar timer em 15 minutos" onClick={()=>{setRunning(false);setSeconds(900)}}><RotateCcw size={18}/></button></div><p>15 minutos são um apoio para começar, não uma regra do cérebro.</p></section><section className="card calendar-card"><span className="eyebrow">SEU CAMINHO</span><h3>Outubro 2026</h3><div className="day-grid">{aulas.map(a=><button key={a.day} title={a.title} aria-label={'Aula '+a.day+': '+a.title} aria-current={day===a.day?'date':undefined} className={(day===a.day?'selected ':'')+(data[key(a.day)]?'done':'')} onClick={()=>select(a.day)}>{data[key(a.day)]?<Check size={16}/>:Number(a.date.slice(-2))}</button>)}</div><small>Verde = concluída. Abra qualquer dia.</small></section><section className="coach"><span className="eyebrow">DICA DO TREINO</span><h3>Perdeu um dia?</h3><p>Retome a próxima aula pendente. Faça 15 minutos se estiver difícil. Não acumule sessões enormes para “pagar dívida”.</p></section></aside></div></TabsContent>
 <TabsContent value="plano"><div className="page-intro"><div><span className="eyebrow">27 DIAS · FOCO EM MAUÁ</span><h1>Você só precisa seguir o próximo dia.</h1><p>05 a 07/10: 30 min. Depois: 45–60 min, divididos se necessário. Simulados: até 2h com correção.</p></div></div><div className="strategy"><div><strong>80%</strong><span>dos pontos em Específicos</span></div><p>Por isso a maior parte das aulas trabalha legislação e atuação da Guarda. As matérias básicas entram em microtreinos e revisões próprias. Esta é uma estratégia pelos pesos, não um levantamento de frequência de questões.</p></div><div className="plan-list">{aulas.map(a=><button key={a.day} className="plan-row" onClick={()=>select(a.day)}><span className={'plan-date '+(data[key(a.day)]?'done':'')}>{data[key(a.day)]?<Check/>:a.date.slice(-2)}<small>OUT</small></span><span><small>{a.kind==='simulado'?'SIMULADO + CORREÇÃO':a.kind==='vespera'?'REVISÃO LEVE':'AULA + MICROTREINO'}</small><b>{a.title}</b><span>{a.reading}</span></span><span className="duration">{a.minutes} min<ChevronRight size={18}/></span></button>)}</div></TabsContent>
 <TabsContent value="treino"><div className="page-intro"><div><span className="eyebrow">PRATICAR PARA LEMBRAR</span><h1>Seu treino de prova.</h1><p>{bank.length} questões autorais. Responda, corrija e explique o motivo.</p></div></div><div className="practice-cards"><button onClick={()=>start('Treino')}><Target/><h3>Treino rápido</h3><p>10 questões de Específicos</p></button><button onClick={()=>start('Simulado')}><Trophy/><h3>Simulado Mauá</h3><p>40 questões · até 100 pontos</p></button><button onClick={()=>start('Erros')}><Brain/><h3>Rever meus erros</h3><p>{wrong.length} questões para recuperar</p></button></div><div className="notice">10 Português, 6 Matemática, 4 Informática e 20 Específicos. Específicos valem 4 pontos cada; os demais, 1. O banco é finito e pode repetir questões.</div>{practice.length?<section className="card"><Quiz key={quizVersion} items={practice} mode={mode} onSave={saveAttempt} ready={ready}/></section>:<section className="card empty"><Target size={35}/><h3>Escolha um treino acima.</h3><p>As questões de cada aula ficam em “Minha aula”.</p></section>}<section className="card"><h2>Histórico deste plano</h2>{attempts.length?attempts.slice(-8).reverse().map(a=><div className="history" key={a.id}><span>{new Date(a.at).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'})} · {a.mode}</span><b>{a.points}/{a.max} {a.mode==='Simulado'?'pontos':'acertos'}</b></div>):<p>Seu primeiro resultado aparecerá ao corrigir um bloco.</p>}</section></TabsContent>
 <TabsContent value="revisao"><div className="page-intro"><div><span className="eyebrow">LEMBRAR SEM OLHAR</span><h1>Revise antes de esquecer.</h1><p>Após concluir uma aula, ela volta em intervalos de 1, 3, 7 e 14 dias entre revisões. Se não lembrar, volta amanhã.</p></div></div>{reviews.length?reviews.map(a=><section className="card" key={a.day}><span className="eyebrow">AULA {a.day}</span><h2>{a.title}</h2><p>{a.recall}</p><details><summary>Conferir depois de tentar</summary><p>{a.answer}</p></details><div className="button-row"><button className="primary" disabled={!ready||busy} onClick={()=>review(a,true)}>Lembrei e expliquei</button><button className="secondary" disabled={!ready||busy} onClick={()=>review(a,false)}>Rever amanhã</button><button className="text-button" onClick={()=>select(a.day)}>Abrir aula</button></div></section>):<section className="card empty"><Brain size={38}/><h2>Nenhuma revisão vencida.</h2><p>Conclua uma aula para iniciar o ciclo. Você pode reabrir qualquer assunto no plano.</p></section>}<section className="card"><h3>Por que funciona assim?</h3><p>Tentar recuperar a informação e receber correção ajuda a aprender; distribuir revisões reduz a dependência de releitura imediata. Os intervalos são uma organização prática, não uma fórmula ideal para todos. Concluir aulas registra esforço, não domínio garantido.</p>{out(sources.science,'Pesquisa sobre recuperação ativa')}{out(sources.spacing,'Pesquisa sobre prática distribuída')}</section></TabsContent>
 <TabsContent value="edital"><div className="page-intro"><div><span className="eyebrow">CONCURSO 02/2026 · IBAM</span><h1>O que não pode passar batido.</h1><p>Plano atualizado para 05/10/2026; fontes consultadas em 01/10. Confira os canais oficiais para retificações e convocação.</p></div></div><section className="card important"><h2>CNH: resolva essa condição desde já.</h2><p>Você informou apenas B. O edital exige <b>A e B</b>. O item 2.6 prevê comprovação na convocação para ingresso; o item 14.9 inclui a documentação. Não há garantia de tempo suficiente para adicionar A. Confirme por escrito com IBAM/Prefeitura e verifique o prazo com Detran/CFC.</p>{out(sources.maua,'Ler edital oficial')}{out(official,'Acompanhar publicações')}</section><div className="facts">{[['PROVA PREVISTA','01/11','3h30 com cartão-resposta'],['INSCRIÇÃO','Até 08/10','23h59 · taxa R$74'],['CONVOCAÇÃO PREVISTA','23/10','Confira local e horário'],['VAGAS TOTAIS','100','Ver modalidades no edital']].map(r=><div key={r[0]}><small>{r[0]}</small><strong>{r[1]}</strong><span>{r[2]}</span></div>)}</div><section className="card"><h2>Checklist de participação</h2>{checklist.map(([id,title,desc])=><label className="checkline admin" key={id}><Checkbox disabled={!ready||busy} checked={!!data['task-maua-admin-'+id]} onCheckedChange={v=>check('task-maua-admin-'+id,v===true)}/><span><b>{title}</b><small>{desc}</small></span></label>)}</section><section className="card"><h2>Como a prova distribui os pontos</h2><div className="table-wrap"><table><thead><tr><th>Matéria</th><th>Questões</th><th>Peso</th><th>Pontos</th></tr></thead><tbody>{[['Português',10,1,10],['Matemática e Raciocínio Lógico',6,1,6],['Informática',4,1,4],['Conhecimentos Específicos',20,4,80]].map(r=><tr key={r[0]}>{r.map((c,i)=><td key={i}>{c}</td>)}</tr>)}</tbody></table></div><p><b>50/100 é mínimo, não garantia de convocação.</b> O Anexo II também exige classificação: 385 na lista geral, 35 PcD, 140 pretos e pardos e 140 mulheres, mais os empates previstos. Confira as regras da sua modalidade. A meta de 80 pontos da central não é nota de corte oficial.</p><p>Ensino médio, idade e altura nos termos do edital, CNH A+B e demais requisitos são obrigatórios. Depois da objetiva há TAF, avaliação psicológica, investigação social, exames médico e toxicológico e formação.</p></section>
 <section className="card"><h2>TAF: não deixe para depois</h2><p>O Anexo III prevê corrida de 50 m, corrida de 12 min, abdominal e flexão de braços. Leia execução, tentativas, índices, atestado e eliminação. Sua prática esportiva não comprova automaticamente os índices.</p>{out(sources.maua+'#page=30','Abrir tabelas do TAF')}<div className="taf-grid">{([['run','Corrida 12 min (m)'],['sprint','Corrida 50 m (s)'],['push','Flexões'],['abs','Abdominais']] as const).map(([id,label])=><label key={id}>{label}<input inputMode="decimal" maxLength={12} value={taf[id]} onChange={e=>setTaf(t=>({...t,[id]:e.target.value}))}/></label>)}</div><button className="secondary" disabled={!ready||busy} onClick={async()=>{setBusy(true);if(await save('taf-maua-oct',taf))toast.success('Registro físico salvo.');setBusy(false)}}>Salvar medição</button><small className="muted">Registro pessoal, sem avaliação automática de aptidão ou prescrição de treino.</small></section>
 <section className="card"><h2>Fontes e provas anteriores</h2><div className="source-list">{[[official,'Prefeitura: acompanhamento'],[sources.maua,'Edital completo e Anexo II'],[sources.municipal,'LC 19/2014 e alterações'],['https://sistemas.maua.sp.gov.br/legislaconsulta/atosofic/Leis%20Complementares/62.pdf','LC 62/2026: carreira'],['https://sistemas.maua.sp.gov.br/legislaconsulta/detalhes.php?nlei=1&tipolei=2','LC 01/2002: servidores'],[sources.past,'Prova anterior IBAM: São Vicente 2025'],[sources.pastOfficial,'IBAM: publicações de São Vicente'],[sources.cf,'Constituição Federal'],[sources.guardas,'Estatuto Geral das Guardas'],[sources.cpp,'Código de Processo Penal'],[sources.cp,'Código Penal'],[sources.maria,'Lei Maria da Penha'],[sources.eca,'ECA'],[sources.abuso,'Abuso de autoridade'],[sources.forca,'Uso da força'],[sources.ctb,'Código de Trânsito Brasileiro']].map(([url,title])=><div key={title}>{out(url,title)}</div>)}</div><p>Provas externas podem exigir acesso ou verificação. As questões da central são autorais. Legislação de outro município não substitui Mauá.</p><div className="notice">O edital considera alterações vigentes até sua publicação, em 11/09/2026. Vídeos antigos e textos compilados atuais podem divergir desse recorte. O PDF da LC 19 não incorpora sozinho todas as alterações. A LC 01 tem leitura guiada, sem consolidação integral aqui. Os resumos e o banco não esgotam todas as hipóteses do programa.</div></section></TabsContent>
 </div><footer>MISSÃO MAUÁ <span>Seu avanço fica salvo nesta central pessoal.</span><small>A aprovação depende de desempenho, classificação e cumprimento de todas as etapas.</small></footer></main></Tabs></>
}
