export type Lesson={id:string;title:string;area:string;scope:string;reading:string;summary:string;recall:string;source:string;video?:string};
export const sources={
maua:'https://dom.maua.sp.gov.br/public/docs/7d240a2e9a5137516a29a7dc49ad17ac.pdf',
gru:'https://anexos-r2.selecao.net.br/uploads/810/concursos/197/anexos/fcca0faf-a472-4459-bb88-d074e3dde6eb.pdf',
cf:'https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm',
guardas:'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2014/lei/l13022.htm',
cpp:'https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689.htm',
cp:'https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848compilado.htm',
maria:'https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11340.htm',
eca:'https://www.planalto.gov.br/ccivil_03/leis/l8069.htm',
abuso:'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2019/lei/l13869.htm',
forca:'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2014/lei/l13060.htm',
ctb:'https://www.planalto.gov.br/ccivil_03/leis/l9503compilado.htm',
idoso:'https://www.planalto.gov.br/ccivil_03/leis/2003/l10.741.htm',
armas:'https://www.planalto.gov.br/ccivil_03/leis/2003/l10.826.htm',
municipal:'https://sistemas.maua.sp.gov.br/legislaconsulta/detalhes.php?nlei=19&tipolei=2',
science:'https://pubmed.ncbi.nlm.nih.gov/18276894/',
spacing:'https://pubmed.ncbi.nlm.nih.gov/16719566/',
past:'https://www.pciconcursos.com.br/provas/download/guarda-civil-municipal-prefeitura-sao-vicente-sp-ibam-2025',
pastOfficial:'https://www.ibamsp-concursos.org.br/informacoes/51/'
};
const rows=[
['guardas','O papel da Guarda Municipal','Legislação','Ambas','Lei 13.022: arts. 1º a 5º','A Guarda é uma instituição civil de proteção preventiva. Diferencie princípios, competência geral e competências específicas. Trabalhar em conjunto com outras instituições não significa substituí-las.','Explique a diferença entre um princípio e uma competência. Dê um exemplo de cada.','guardas','uzv-IYyfCck'],
['guardas2','Carreira, controle e formação','Legislação','Ambas','Lei 13.022: arts. 6º a 22','A lei separa criação, ingresso, capacitação, fiscalização e prerrogativas. A corregedoria exerce controle interno; a ouvidoria, externo. Requisitos locais podem complementar os nacionais.','Quem exerce cada controle? Quando a corregedoria é exigida?','guardas','lVJTRTqpTbk'],
['texto','Ler o que o texto realmente diz','Português','Ambas','Interpretação: informação explícita e inferência','Informação explícita aparece no texto. Inferência é uma conclusão sustentada por pistas. Extrapolação acrescenta uma afirmação sem apoio. Justifique a alternativa com um trecho, não com sua opinião.','Crie um exemplo de inferência e outro de extrapolação.','maua'],
['cf5','Direitos fundamentais em situações reais','Legislação','Ambas','Constituição: art. 5º, leitura em blocos','Liberdades e garantias limitam a atuação estatal. Ao estudar inviolabilidade do domicílio, separe a regra das exceções e observe a exigência de período diurno para ordem judicial.','Quais exceções permitem entrar em casa sem consentimento?','cf'],
['percent','Porcentagem sem decorar atalhos','Matemática','Ambas','Percentual, desconto e aumento','p% equivale a p/100. Um desconto de 20% multiplica o preço por 0,80. Aumentos sucessivos usam fatores: 1,10 × 1,10 = 1,21. A base muda a cada operação.','Um item de R$200 aumenta 10% e cai 10%. Por que não volta a R$200?','maua','IzTLejT9u38'],
['cf144','Segurança pública e Administração','Legislação','Ambas','CF art. 144; art. 37 para Mauá; art. 6º para Guarulhos','No art. 144, distinga órgãos e atribuições. Para Mauá, estude também os princípios expressos da Administração: legalidade, impessoalidade, moralidade, publicidade e eficiência. Para Guarulhos, revise os direitos sociais.','Explique publicidade e impessoalidade com situações diferentes.','cf'],
['local1','Mauá: estrutura e atribuições','Legislação','Mauá','LC 19/2014: finalidade, organização, atribuições; conferir LC 62/2026','Leitura guiada da legislação municipal, não resumo integral validado: monte duas colunas, unidade e atribuição. Não use a norma revogada de 2005. Confira o texto vigente e as alterações antes de memorizar.','Quais atribuições pertencem à 3ª classe? Registre o dispositivo encontrado.','municipal'],
['word','Arquivos, Word e atalhos','Informática','Ambas','Gerenciamento de arquivos; edição e formatação','Copiar mantém o original; mover altera a localização. No editor, diferencie alinhamento, recuo, espaçamento e margem. Atalhos variam por programa e idioma: treine no ambiente cobrado.','Qual a diferença entre margem e recuo? E entre copiar e mover?','maua'],
['flagrante','Prisão em flagrante','Legislação','Ambas','CPP arts. 301 a 310','Qualquer pessoa pode prender em flagrante; autoridades policiais e seus agentes devem fazê-lo. Diferencie estar cometendo, acabar de cometer, perseguição logo após e encontro logo depois nas condições legais.','Crie uma situação para cada hipótese do art. 302.','cpp'],
['concord','Concordância e termos da oração','Português','Ambas','Sujeito, verbo, concordância nominal e verbal','Encontre o núcleo do sujeito antes de flexionar o verbo. Haver com sentido de existir fica no singular; existir concorda com o sujeito. Fazer indicando tempo decorrido também é impessoal.','Corrija: houveram problemas; faziam dois anos; existe vagas.','maua'],
['abuso','Abuso de autoridade','Legislação','Ambas','Lei 13.869/2019: sujeitos, finalidade e tipos penais','A lei exige finalidade específica: prejudicar alguém, beneficiar a si ou terceiro, capricho ou satisfação pessoal. Não confunda divergência de interpretação, isoladamente, com crime de abuso.','Todo erro de interpretação é abuso? Justifique com a lei.','abuso','BtzCYT-0WjE'],
['regra','Razão, proporção e regra de três','Matemática','Ambas','Grandezas diretas e inversas; composta em Guarulhos','Antes de multiplicar cruzado, pergunte se aumentar uma grandeza faz a outra aumentar ou diminuir. Mantido o serviço e o ritmo, mais trabalhadores exigem menos tempo.','Quatro agentes levam seis horas. Seis agentes levam quanto tempo?','maua','IzTLejT9u38'],
['maria','Violência doméstica: reconhecer as formas','Legislação','Ambas','Lei Maria da Penha: arts. 1º a 7º; medidas protetivas para Mauá','Violência doméstica não se resume à agressão física. Diferencie dano corporal, controle psicológico, ofensa moral, violência sexual e retenção de bens. Consulte a redação vigente: listas de vídeos antigos podem estar desatualizadas.','Reter documentos caracteriza qual forma? Crie também um exemplo de violência moral.','maria','rucJGwqYHhs'],
['local2','Mauá: disciplina e responsabilidades','Legislação','Mauá','LC 19/2014: deveres, transgressões e penalidades; LC 01/2002','Leitura guiada: construa uma tabela de dever, proibição e consequência. Registre a autoridade competente e os prazos somente após conferir o dispositivo. Este guia não substitui as leis municipais.','Escolha duas proibições e explique como poderiam aparecer em uma situação de prova.','municipal'],
['eca','Criança, adolescente e proteção','Legislação','Ambas','ECA: direitos, prevenção, proteção e ato infracional; Guarulhos arts. 1–6, 103–109, 131–137, 225–244-B','Criança tem menos de 12 anos; adolescente, de 12 a menos de 18. Ato infracional corresponde a conduta descrita como crime ou contravenção. Não confunda medidas de proteção com medidas socioeducativas.','O que muda entre criança e adolescente? Defina ato infracional.','eca','ad5e9qr3gew'],
['excel','Excel e segurança digital','Informática','Ambas','Referências, SOMA, MÉDIA, filtros, phishing e backup','A1:A5 é um intervalo. Referências absolutas usam $. Filtrar oculta linhas que não atendem aos critérios, sem apagá-las. Desconfie de urgência, links e pedidos de senha; confira o canal oficial.','Qual a diferença entre SOMA e MÉDIA? Como identificar uma tentativa de phishing?','maua'],
['penal','Furto, roubo, ameaça e lesão','Legislação','Ambas','CP: tipos previstos nos dois editais; foco nos elementos de cada crime','Compare os verbos do tipo penal. Furto envolve subtração; roubo acrescenta violência ou grave ameaça, nas hipóteses legais. Ameaça e lesão corporal têm elementos próprios. Não decore penas antes de entender a conduta.','Por que retirar um objeto escondido difere de tomá-lo com grave ameaça?','cp'],
['crase','Crase, regência e pronomes','Português','Ambas','Regência verbal e nominal; crase; colocação pronominal','Crase pode reunir a preposição a e o artigo a. Antes de verbo não ocorre essa fusão. Faça o teste do masculino quando aplicável: dirigir-se ao posto / à unidade.','Explique por que há crase em dirigir-se à escola e não em começar a estudar.','maua'],
['forca','Uso da força e proporcionalidade','Legislação','Ambas','Lei 13.060/2014; Decreto 12.341/2024 em Guarulhos','A escolha do meio depende da necessidade e do risco. A lei veda disparo contra fugitivo desarmado sem risco imediato de morte ou lesão. Preveja assistência quando o uso da força causar ferimentos.','Fugir, por si só, autoriza disparo? Explique a condição legal.','forca'],
['ctb','Trânsito: circulação e sinalização','Legislação','Mauá','CTB: circulação, pedestres, sinalização e agentes','Estude a ordem de prevalência da sinalização. Separe infração, penalidade e medida administrativa: são categorias distintas. Faça exemplos próprios de prioridade e de circulação segura.','Ordens do agente prevalecem sobre o semáforo? Qual a diferença entre penalidade e medida?','ctb'],
['logica','Lógica, frações e equações','Matemática','Ambas','Operações, equação de 1º grau, sequências; proposições em Mauá','Negar todo exige ao menos uma exceção, não a negação de todos os casos. Em equações, aplique a mesma operação aos dois membros. Em sequências, teste o padrão em todos os termos.','Negue: todos estudaram. Resolva 3x + 6 = 21 e confira.','maua'],
['custodia','Cadeia de custódia e preservação','Legislação','Mauá','CPP arts. 158-A a 158-F','A cadeia documenta a trajetória do vestígio. Preservação, registro e rastreabilidade são centrais. Diferencie reconhecimento, isolamento, fixação, coleta, acondicionamento e demais etapas da lei.','Por que registrar quem recebeu o vestígio importa?','cpp'],
['operacional','Atuação preventiva e conflitos','Legislação','Mauá','Segurança urbana, atendimento, calamidades e integração','Use situações de atendimento para distinguir prevenção, comunicação e encaminhamento. Escutar e esclarecer não significa abandonar a segurança. As respostas devem respeitar atribuições e direitos, sem assumir poderes inexistentes.','Descreva uma abordagem verbal que reduza tensão sem prometer o que você não pode cumprir.','guardas'],
['socorros','Socorros e prevenção de incêndios','Legislação','Mauá','Leitura orientada dos tópicos do edital; complementar com treinamento qualificado','Este módulo é roteiro de estudo, não treinamento de emergência. Revise segurança da cena, acionamento de ajuda e reconhecimento de sinais de gravidade. Não pratique procedimentos em colegas sem instrutor.','Quais informações devem ser passadas ao serviço de emergência?','maua'],
['local3','Mauá: ingresso e atualização da carreira','Legislação','Mauá','LC 62/2026; formação, estágio probatório e atribuições','A alteração de 2026 deve ser comparada ao Estatuto. Marque dispositivo alterado e redação atual. O edital exige CNH A e B; sua categoria B precisa ser complementada para assumir conforme as exigências.','Quais três requisitos ou regras mudaram? Anote a referência consultada.','maua'],
['pontua','Pontuação, coesão e reescrita','Português','Ambas','Conjunções, pontuação, períodos, sentido literal e figurado','Pontuação organiza relações de sentido. Não separe sujeito e verbo por vírgula. Na reescrita, preserve tanto a correção quanto o sentido. Embora indica concessão; portanto indica conclusão.','Trocar embora por portanto mantém a relação de sentido? Por quê?','maua'],
['medidas','Medidas, médias e gráficos','Matemática','Ambas','Unidades, média; tabelas, gráficos e sistemas em Guarulhos','Converta tudo para a mesma unidade antes de calcular. Média simples é soma dividida pela quantidade. Gráficos exigem atenção à escala, unidade e período, não apenas à altura das colunas.','Qual a média de 6, 8 e 10? Quantos minutos há em 2,5 horas?','gru'],
['idoso','Pessoa idosa: direitos e crimes','Legislação','Guarulhos','Lei 10.741: arts. 1º a 7º e 95 a 108','O Estatuto protege pessoas de 60 anos ou mais. Separe direitos e deveres de proteção das condutas criminalizadas. Treine reconhecimento de discriminação, abandono e retenção indevida de recursos nos termos legais.','Qual a idade prevista? Como distinguir uma garantia de um crime?','idoso','ad5e9qr3gew'],
['armas','Desarmamento: porte e crimes','Legislação','Guarulhos','Lei 10.826: arts. 6º a 11 e 12 a 21','Posse, porte e registro não são sinônimos. Leia as hipóteses específicas de autorização e os elementos das condutas. Não generalize permissões de uma categoria para qualquer pessoa.','Por que ter registro não equivale a autorização irrestrita para portar?','armas'],
['penal2','Crimes contra a Administração','Legislação','Guarulhos','CP arts. 312 a 327; complementar arts. 121–129, 146–150, 155–159','Peculato envolve apropriação ou desvio nas condições legais. Concussão tem como verbo exigir; corrupção passiva inclui solicitar ou receber vantagem indevida. Compare sujeitos, verbos e relação com a função.','Diferencie exigir de solicitar vantagem indevida nos tipos penais.','cp'],
['gru1','Guarulhos: legislação da carreira','Legislação','Guarulhos','Lei Municipal 7.792/2019','Leitura guiada pendente de conferência integral: localize a lei no portal municipal indicado pelo edital. Divida a leitura em estrutura, deveres e regime disciplinar. Não reutilize regras de Mauá.','Liste três regras locais e identifique o artigo correspondente.','gru'],
['gru2','Guarulhos: estrutura e decreto','Legislação','Guarulhos','Lei 8.361/2025 arts. 166–170; Decreto 44.264/2026','Roteiro de leitura, não resumo validado do decreto: relacione cada órgão à sua competência e confira o decreto de julho de 2026 vinculado no edital. Normas locais precisam ser estudadas separadamente.','Quais competências aparecem nos artigos 166 a 170?','gru'],
['info2','Windows, apresentações e nuvem','Informática','Guarulhos','Windows 10/11, hardware, slides, PDF e compartilhamento','Hardware é componente físico; software é programa. Sincronização em nuvem não elimina a necessidade de backup. Permissões de compartilhamento podem permitir só leitura ou edição; revise antes de enviar.','Qual o risco de compartilhar um documento com permissão de edição?','gru']
];
export const lessons:Lesson[]=rows.map(r=>({id:r[0],title:r[1],area:r[2],scope:r[3],reading:r[4],summary:r[5],recall:r[6],source:sources[r[7] as keyof typeof sources],video:r[8]}));
export type Question={id:string;lesson:string;area:string;q:string;options:string[];correct:number;why:string};
const qs:any[]=[
['texto','Português','“As ocorrências caíram no centro; nos bairros, permaneceram estáveis.” O texto permite concluir que:',['Houve redução em toda a cidade','A redução não ocorreu igualmente nas duas regiões','Os bairros ficaram mais violentos','O centro não teve alteração'],1,'O contraste é entre queda e estabilidade; não há aumento informado.'],
['texto','Português','“A equipe chegou cedo, mas o evento já havia começado.” O termo mas expressa:',['Conclusão','Causa','Adição','Oposição'],3,'Mas liga ideias em contraste.'],
['texto','Português','Em “o agente recolheu o documento e o guardou”, o segundo o retoma:',['O agente','O documento','O local','O ato de recolher'],1,'O pronome substitui documento, complemento de guardou.'],
['concord','Português','Qual frase segue a norma-padrão?',['Houveram falhas','Fazem dois anos','Existem vagas','Existe muitas pessoas'],2,'Existem concorda com vagas; haver existencial e fazer temporal são impessoais.'],
['concord','Português','Em “Os moradores da rua solicitaram ajuda”, o núcleo do sujeito é:',['moradores','rua','ajuda','solicitaram'],0,'Moradores é o núcleo; da rua apenas o caracteriza.'],
['crase','Português','Qual forma está correta?',['Começou à estudar','Dirigiu-se à unidade','Ficou frente à frente','Entregou à ele'],1,'Dirigir-se exige a; unidade admite artigo a.'],
['pontua','Português','Qual frase NÃO separa indevidamente sujeito e verbo?',['Os guardas, chegaram cedo.','A equipe do bairro, atendeu.','Os moradores da praça, pediram ajuda.','Ao amanhecer, a equipe chegou.'],3,'A vírgula separa um adjunto deslocado, não sujeito e verbo.'],
['pontua','Português','“Embora estivesse cansado, estudou.” Embora indica:',['Concessão','Finalidade','Conclusão','Alternância'],0,'Concessão apresenta um obstáculo que não impediu o estudo.'],
['texto','Português','Qual reescrita preserva “A equipe agiu com rapidez”?',['A equipe quase agiu','A equipe agiu rapidamente','A equipe deveria agir','A equipe demorou'],1,'Rapidamente equivale a com rapidez.'],
['concord','Português','Complete: As informações estavam ___.',['correto','correta','corretas','corretos'],2,'O adjetivo concorda no feminino plural com informações.'],
['percent','Matemática','Um produto de R$250 recebe desconto de 12%. Qual o novo preço?',['R$220','R$230','R$238','R$280'],0,'250 × 0,12 = 30; 250 − 30 = 220.'],
['percent','Matemática','R$200 aumenta 10% e depois diminui 10%. O resultado é:',['R$200','R$202','R$180','R$198'],3,'200 × 1,10 × 0,90 = 198.'],
['regra','Matemática','4 agentes fazem um serviço em 6 horas. Com o mesmo ritmo, 6 agentes levarão:',['3 h','4 h','6 h','9 h'],1,'São 24 agente-horas: 24 ÷ 6 = 4.'],
['logica','Matemática','A negação de “Todos estudaram” é:',['Ninguém estudou','Todos faltaram','Pelo menos um não estudou','Alguém estudou'],2,'Uma exceção é suficiente para negar uma afirmação universal.'],
['medidas','Matemática','A média de 6, 8 e 10 é:',['8','9','12','24'],0,'(6+8+10) ÷ 3 = 8.'],
['logica','Matemática','Na equação 3x + 6 = 21, x vale:',['3','7','9','5'],3,'3 × 5 + 6 = 21.'],
['excel','Informática','Qual fórmula calcula a média de A1 até A5 no Excel em português?',['=SOMA(A1:A5)','=MÉDIA(A1:A5)','=MÁXIMO(A1:A5)','=CONT.NÚM(A1:A5)'],1,'MÉDIA retorna a média aritmética dos números do intervalo.'],
['excel','Informática','Uma referência absoluta de célula é:',['A1','A$1','$A$1','$A1'],2,'Os dois símbolos $ fixam coluna e linha.'],
['excel','Informática','Uma mensagem falsa pedindo senha bancária por um link é exemplo de:',['Backup','Compactação','Atualização','Phishing'],3,'Phishing tenta enganar a vítima para obter dados ou acesso.'],
['word','Informática','Copiar um arquivo, diferentemente de movê-lo, normalmente:',['Mantém o original no local de origem','Apaga o original','Muda a extensão','Remove permissões de todos'],0,'A cópia cria outra instância sem retirar a original.'],
['info2','Informática','Qual é um exemplo de hardware?',['Navegador','Memória RAM','Editor de texto','Sistema operacional'],1,'RAM é um componente físico.'],
['guardas','Legislação','Segundo a Lei 13.022, a natureza da instituição Guarda Municipal é:',['Militar','Judicial','Civil','Privada'],2,'Art. 2º: instituição civil, uniformizada e armada conforme a lei.'],
['guardas','Legislação','Qual é um princípio mínimo da Lei 13.022?',['Preservação da vida','Punição imediata sem processo','Sigilo de todas as ações','Substituição da polícia judiciária'],0,'Art. 3º inclui preservar a vida e reduzir sofrimento e perdas.'],
['guardas','Legislação','A GCM pode, nas condições legais:',['Julgar crimes','Criar penas','Presidir qualquer inquérito','Colaborar com órgãos de segurança em ações conjuntas'],3,'Art. 5º prevê colaboração integrada, sem assumir atribuições judiciais.'],
['guardas2','Legislação','Na Lei 13.022, a ouvidoria exerce controle:',['Interno disciplinar','Externo','Judicial','Militar'],1,'O controle externo cabe à ouvidoria independente da direção da guarda.'],
['guardas2','Legislação','A Guarda Municipal é subordinada ao:',['Presidente do tribunal','Comandante do Exército','Chefe do Executivo municipal','Presidente da Câmara'],2,'Art. 6º, parágrafo único, indica o chefe do Executivo municipal.'],
['guardas2','Legislação','O município cria sua guarda por:',['Lei','Ordem verbal','Portaria de escola','Decisão de associação'],0,'Art. 6º exige lei municipal.'],
['cf5','Legislação','A entrada em domicílio por determinação judicial, sem consentimento, é constitucionalmente prevista:',['A qualquer hora, sempre','Apenas nos feriados','Somente à noite','Durante o dia'],3,'Art. 5º, XI: ordem judicial durante o dia; as outras exceções são distintas.'],
['cf144','Legislação','No art. 144, segurança pública é responsabilidade:',['Somente das polícias','De todos','Só dos municípios','Só dos tribunais'],1,'É dever estatal e direito e responsabilidade de todos.'],
['cf5','Legislação','A manifestação do pensamento é livre, mas é vedado:',['O direito de resposta','O debate','O anonimato','O pedido de informação'],2,'Art. 5º, IV, veda o anonimato.'],
['flagrante','Legislação','Segundo o art. 301 do CPP, qualquer pessoa:',['Pode prender quem esteja em flagrante','Deve investigar o crime','Pode condenar o autor','Só pode comunicar, nunca prender'],0,'A faculdade é de qualquer pessoa; o dever é das autoridades policiais e seus agentes.'],
['flagrante','Legislação','Qual situação está expressamente no art. 302 do CPP?',['Suspeita sem qualquer indício','Crime ocorrido há anos, sem perseguição','Absolvição definitiva','Acabar de cometer a infração'],3,'Acabar de cometer a infração é hipótese de flagrante próprio.'],
['abuso','Legislação','A Lei de Abuso de Autoridade exige:',['Qualquer erro, mesmo involuntário','Finalidade específica prevista na lei','Apenas prejuízo financeiro','Somente cargo vitalício'],1,'Art. 1º, §1º, exige propósito específico, não mera falha.'],
['abuso','Legislação','Divergência na interpretação de lei, isoladamente:',['Sempre configura abuso','Dispensa processo','Não configura abuso de autoridade','É crime hediondo'],2,'Art. 1º, §2º, afasta essa caracterização isolada.'],
['maria','Legislação','Reter documentos e recursos da mulher nas condições da Lei Maria da Penha é violência:',['Patrimonial','Física','Exclusivamente sexual','Somente moral'],0,'Art. 7º inclui retenção e subtração de documentos e recursos na forma patrimonial.'],
['maria','Legislação','Calúnia, difamação ou injúria, na Lei Maria da Penha, caracterizam violência:',['Patrimonial','Física','Sexual','Moral'],3,'O art. 7º, V, relaciona essas condutas à violência moral.'],
['eca','Legislação','Para o ECA, é criança a pessoa:',['Até 14 anos completos','Com menos de 12 anos','Até 16 anos','Somente até 6 anos'],1,'Art. 2º: até 12 anos incompletos.'],
['eca','Legislação','Ato infracional corresponde à conduta descrita como:',['Somente desobediência familiar','Qualquer falta escolar','Crime ou contravenção penal','Apenas crime hediondo'],2,'Art. 103 traz essa definição.'],
['penal','Legislação','Subtrair bem com grave ameaça, nas condições do tipo penal, caracteriza:',['Roubo','Furto simples','Apenas dano','Apenas desacato'],0,'A grave ameaça na subtração distingue roubo do furto simples.'],
['forca','Legislação','A fuga desarmada, sem risco imediato de morte ou lesão, autoriza disparo?',['Sempre','Se houver pressa','Se o agente preferir','Não'],3,'Lei 13.060, art. 2º: o disparo é ilegítimo nessa hipótese.'],
['guardas2','Legislação','A idade mínima nacional prevista na Lei 13.022 é:',['16 anos','18 anos','21 anos','25 anos'],1,'Art. 10 estabelece 18 anos, sem dispensar demais requisitos.'],
['ctb','Legislação','Na sinalização de trânsito, prevalece sobre as demais regras:',['A placa de publicidade','A preferência pessoal','A ordem do agente de trânsito','A buzina'],2,'CTB art. 89 coloca as ordens do agente acima das normas e sinais.'],
['custodia','Legislação','A cadeia de custódia busca principalmente:',['Documentar a trajetória do vestígio','Substituir o juiz','Dispensar perícia','Ocultar o coletor'],0,'CPP art. 158-A define documentação da história cronológica do vestígio.'],
['idoso','Legislação','O Estatuto da Pessoa Idosa alcança pessoas a partir de:',['65 anos','70 anos','55 anos','60 anos'],3,'Art. 1º estabelece idade igual ou superior a 60 anos.'],
['penal2','Legislação','O verbo característico da concussão é:',['Pedir desculpas','Exigir vantagem indevida','Prestar auxílio','Esquecer'],1,'CP art. 316 descreve exigir vantagem indevida em razão da função.']
];
export const questions:Question[]=qs.map((q,i)=>({id:'q'+(i+1),lesson:q[0],area:q[1],q:q[2],options:q[3],correct:q[4],why:q[5]}));
export function dateKey(d:Date){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
const first=['guardas','texto','guardas2','cf5','percent','cf144','local1','word','flagrante','concord','abuso','regra','maria','local2','eca','excel','penal','crase','forca','ctb','logica','custodia','operacional','socorros','local3','pontua','medidas'];
const second=['idoso','armas','penal2','gru1','gru2','info2','cf5','flagrante','abuso','maria','eca','forca','guardas2','texto','medidas','excel','penal2','gru1','gru2'];
export const plan=Array.from({length:75},(_,i)=>{
 const d=new Date(Date.UTC(2026,8,16+i,15));const date=d.toISOString().slice(0,10);const dow=d.getUTCDay();
 const pre=i<46;const n=pre?Array.from({length:i},(_,j)=>new Date(Date.UTC(2026,8,16+j,15)).getUTCDay()).filter(x=>x!==0&&x!==6).length:Array.from({length:i-47},(_,j)=>new Date(Date.UTC(2026,10,2+j,15)).getUTCDay()).filter(x=>x!==0&&x!==6).length;
 const pool=pre?first:second;const lesson=pool[Math.max(0,n)%pool.length];
 const kind=i===46||i===74?'exam':(i===45||i===73)?'light':dow===0?'rest':dow===6?'mock':'lesson';
 const minutes=kind==='rest'?10:kind==='exam'?0:kind==='light'?20:kind==='mock'?(i<14?40:90):i<7?30:i<14?40:50;
 return {id:date,date,index:i,kind,lesson,minutes,title:kind==='exam'?(i===46?'Prova de Mauá':'Prova de Guarulhos'):kind==='rest'?'Revisão leve e descanso':kind==='mock'?'Simulado + correção dos erros':kind==='light'?'Véspera: revisão leve e organização':lessons.find(l=>l.id===lesson)!.title};
});
