import {questions as oldQuestions,lessons as oldLessons,sources,Question} from './curriculum';
export {sources};
export const official='https://www.maua.sp.gov.br/Concursos/Detalhes/2026/7';
const local62='https://sistemas.maua.sp.gov.br/legislaconsulta/atosofic/Leis%20Complementares/62.pdf';
const local1='https://sistemas.maua.sp.gov.br/legislaconsulta/detalhes.php?nlei=1&tipolei=2';
const aid='https://www.samu.ce.gov.br/primeiros-socorros/';
export type Aula={originalDay?:number;topics?:string[];moreSources?:{url:string;label:string}[];day:number;date:string;title:string;topic:string;minutes:number;kind:string;reading:string;url:string;parts:string[];analogy:string;trap:string;recall:string;answer:string;video?:string;videoTitle?:string;extra:string};
const a=(day:number,title:string,topic:string,reading:string,url:string,parts:string[],analogy:string,trap:string,recall:string,answer:string,video='',videoTitle='',kind='aula'):Aula=>({day,date:`2026-10-${String(day).padStart(2,'0')}`,title,topic,reading,url,parts,analogy,trap,recall,answer,video,videoTitle,kind,minutes:kind==='simulado'?120:day===31?20:day<=3?30:45,extra:''});
const baseAulas:Aula[]=[
a(1,'O que a Guarda faz de verdade','guardas','Lei 13.022/2014 • arts. 1º a 5º',sources.guardas,[
'A Guarda Municipal é uma instituição de caráter civil, uniformizada e armada conforme a lei. Sua função é a proteção municipal preventiva. Prevenir significa agir para reduzir a chance de um problema ocorrer, e não apenas chegar depois.',
'Os princípios do art. 3º orientam COMO agir: direitos humanos, cidadania e liberdades; preservação da vida; patrulhamento preventivo; compromisso com a evolução social da comunidade; uso progressivo da força. Competências dizem O QUE fazer.',
'A competência geral protege bens, serviços, logradouros e instalações municipais. Entre as específicas estão proteção escolar, colaboração com a defesa civil, mediação de conflitos e encaminhamento ao delegado em flagrante, preservando o local quando possível e necessário. Leia os incisos do art. 5º e associe cada um a uma situação.'
],'No vôlei, “respeitar os jogadores” é um princípio; “receber o saque” é uma tarefa. Na Guarda, respeitar a vida orienta a atuação; patrulhar a escola é uma competência. A comparação ajuda a separar COMO e O QUE, sem transformar regra esportiva em lei.','A Guarda é civil. Atuar integrada com outros órgãos não permite ignorar atribuições legais.','Diga um princípio e duas competências sem olhar.','Princípio: preservação da vida. Competências: proteção escolar e colaboração com a defesa civil.','uzv-IYyfCck','Aula: Estatuto Geral das Guardas Municipais'),
a(2,'Quem fiscaliza a Guarda?','guardas2','Lei 13.022 • arts. 6º a 22',sources.guardas,[
'O município pode criar sua guarda por lei. A lei nacional fixa limites de efetivo relacionados à população e requisitos básicos de ingresso; a legislação municipal pode estabelecer outros requisitos. Não troque requisito nacional por uma exigência local.',
'Capacitação é específica para o exercício da função. Corregedoria faz controle interno nas guardas com mais de 50 servidores e em todas as que utilizam arma de fogo. Ouvidoria faz controle externo, independente da direção da guarda, qualquer que seja o efetivo.',
'O código de conduta é próprio, conforme lei municipal; a guarda não pode ficar sujeita a regulamento disciplinar de natureza militar. Corregedoria e ouvidoria têm funções diferentes: fiscalização disciplinar interna versus receber e encaminhar manifestações da população.'
],'Pense na comissão técnica avaliando o time e num canal independente que recebe reclamações dos torcedores. É uma ponte para lembrar “interno” e “externo”; a competência real está no art. 13.','Não é “mais de 50 E armada”. São duas hipóteses para corregedoria: mais de 50 OU uso de arma.','Uma guarda armada com 30 servidores precisa de corregedoria?','Sim. A exigência alcança todas as guardas que utilizam arma de fogo.','uzv-IYyfCck','Estatuto Geral • continue nos capítulos de controle e capacitação'),
a(3,'Constituição: o regulamento maior','cf1','Constituição • arts. 1º a 4º',sources.cf,[
'Os fundamentos do art. 1º são soberania, cidadania, dignidade da pessoa humana, valores sociais do trabalho e da livre iniciativa e pluralismo político. Fundamento é a base do Estado. Todo poder emana do povo.',
'Os Poderes da União são Legislativo, Executivo e Judiciário, independentes e harmônicos. Os objetivos do art. 3º apontam resultados: sociedade livre, justa e solidária; desenvolvimento; redução de desigualdades e erradicação da pobreza e marginalização; bem de todos sem discriminação.',
'O art. 4º trata das relações internacionais: defesa da paz, direitos humanos, não intervenção e solução pacífica dos conflitos, entre outros. Separe em três caixas: fundamento = base; objetivo = resultado; relação internacional = relação com outros Estados.'
],'Um campeonato tem valores que o sustentam, metas que deseja alcançar e regras de relação entre equipes. O Brasil também distingue bases, objetivos e relações internacionais.','“Garantir o desenvolvimento nacional” é objetivo, não fundamento.','Dignidade, desenvolvimento nacional e defesa da paz entram em quais caixas?','Fundamento, objetivo e princípio das relações internacionais, respectivamente.','apBfELZgtNk','Constituição Federal • arts. 1º a 4º'),
a(4,'Direitos que limitam a atuação estatal','cf5','Constituição • art. 5º, especialmente II, III, XI, XVI, LIV a LXVIII',sources.cf,[
'Ninguém é obrigado a agir ou deixar de agir senão em virtude de lei. Tortura e tratamento desumano são proibidos. A pessoa investigada também tem direitos: acusação não elimina dignidade nem defesa.',
'A casa é inviolável. Sem consentimento, a Constituição admite entrada em flagrante delito, desastre, para prestar socorro ou, durante o dia, por determinação judicial. A exigência “durante o dia” está ligada à ordem judicial; não invente autorização baseada só em suspeita vaga.',
'Há devido processo legal, contraditório e ampla defesa. O preso deve ser informado de seus direitos, inclusive permanecer calado, e ter assistência da família e de advogado. Habeas corpus protege a liberdade de locomoção ameaçada ou violada ilegalmente. Reunião pacífica e sem armas exige prévio aviso, não autorização, nos termos constitucionais.'
],'Se um jogador é acusado de quebrar o regulamento, isso não autoriza humilhação nem punição inventada. A analogia ajuda a lembrar limites e defesa; as garantias constitucionais têm alcance próprio.','Aviso não é autorização. Silêncio não equivale a confissão.','Qual exceção para entrar numa casa está limitada ao dia no texto constitucional?','A entrada por determinação judicial. Flagrante, desastre e socorro não têm essa limitação no inciso XI.','c1J-lir22cE','Constituição de 1988 • revisão do art. 5º'),
a(5,'LIMPE e segurança pública','cf144','Constituição • arts. 37 e 144',sources.cf,[
'LIMPE reúne os princípios expressos do art. 37: legalidade, impessoalidade, moralidade, publicidade e eficiência. O agente age conforme a lei, busca o interesse público, mantém conduta ética, dá transparência nos limites legais e utiliza bem os recursos.',
'Impessoalidade impede favorecimento pessoal. Publicidade não elimina sigilos legítimos. Eficiência não autoriza atalhos ilegais. Concurso é a regra para investidura em cargo ou emprego público, ressalvadas as hipóteses constitucionais.',
'Segurança pública é dever do Estado, direito e responsabilidade de todos. Leia os órgãos e competências do art. 144. O § 8º autoriza os municípios a constituírem guardas para proteção de seus bens, serviços e instalações conforme a lei; relacione a redação com a Lei 13.022 e precedentes pertinentes anteriores ao edital.'
],'O técnico não pode escalar o sobrinho por favoritismo num processo que deveria seguir critérios públicos. Isso lembra impessoalidade. Aproveitar bem o treino lembra eficiência, sem dispensar as regras.','Publicidade não significa expor dados protegidos de vítimas.','Usar menos recursos justifica descumprir a lei?','Não. Eficiência deve conviver com legalidade e os demais princípios.','Mrxcy5GGWiI','Complemento constitucional • arts. 1º a 5º; leia 37 e 144 na fonte'),
a(6,'Mauá: organização e trabalho preventivo','local1','LC 19/2014 • arts. 1º a 23; ler junto das alterações',sources.municipal,[
'A Guarda de Mauá é civil, uniformizada e armada, organizada com hierarquia e disciplina. O art. 4º prevê patrulhamento preventivo e comunitário, interação com polícias estaduais, mediação de conflitos, proteção do patrimônio e prioridade à segurança escolar.',
'O art. 6º subordina a Guarda à Secretaria de Segurança Pública Municipal. O Estatuto organiza comando, divisões administrativas, operacionais e de formação. O comando planeja; o suporte administrativo organiza recursos; a formação capacita. Leia os artigos para ligar cada unidade à sua atribuição.',
'A corregedoria tem autonomia em relação ao comando para as funções previstas. O PDF de 2014 não é uma consolidação completa: use a página de alterações e a LC 62/2026. Não memorize do texto antigo idade máxima de 30 anos nem ingresso na 2ª classe.'
],'Um time tem técnico, apoio que organiza material e comissão que prepara os atletas. Na Guarda também existem funções distintas: receber uma ordem não torna todos responsáveis pela mesma atribuição.','Instituição armada e hierarquizada continua sendo civil.','Que duas atuações preventivas a lei local prevê?','Patrulhamento comunitário e prevenção de delitos, com prioridade à segurança escolar. A mediação de conflitos também aparece.','uzv-IYyfCck','Complemento nacional • a regra local está na leitura desta aula'),
a(7,'A mudança de 2026: ingresso e formação','local3','LC 62/2026 • arts. 1º a 9º',local62,[
'A nova classe inicial é GCM de 3ª Classe. Requisitos: ensino médio completo; CNH válida A e B; altura mínima de 1,60 m para homens e 1,55 m para mulheres; idade de 18 a 35 anos conforme os marcos indicados no edital e na lei.',
'O art. 52-A atribui à 3ª Classe proteção patrimonial, rondas, controle de acesso de pessoas, veículos e equipamentos, função de motociclista e motorista, comunicação de irregularidades à chefia, urbanidade e colaboração em socorro e prevenção de incêndios.',
'O GCM Aluno recebe bolsa de 50% do vencimento inicial da 3ª Classe. A lei usa “média superior a 70%” no curso. O estágio probatório é de três anos; confirmado, há promoção à 2ª Classe no dia seguinte à homologação da estabilidade. A LC 62 entrou em vigor após 45 dias da publicação.'
],'Entrar no elenco principal é diferente de estar em formação. A lei separa aluno, aprovação no curso e estágio no cargo. Não trate as etapas como se fossem um único “passei”.','“Superior a 70%” não é igual a “70% ou mais”. Sua CNH B sozinha não cumpre o requisito A+B.','Qual a classe de entrada e quanto dura o estágio probatório?','3ª Classe e três anos, conforme a redação de 2026.','uzv-IYyfCck','Complemento: formação nacional; as novidades locais estão nesta aula'),
a(8,'Disciplina não é obediência cega','local2','LC 19/2014 • arts. 42, 81 a 84 e 97',sources.municipal,[
'Hierarquia organiza níveis de responsabilidade. Disciplina envolve cumprir as regras e os deveres da função. O comandante deve observar legalidade, cooperação, respeito e prévia oportunidade de ampla defesa na aplicação de penalidades.',
'O art. 81 prevê regulamento próprio com princípios de disciplina e hierarquia, deveres, proibições, responsabilidades, transgressões e procedimentos. O art. 82 lista advertência verbal, advertência escrita, suspensão e demissão.',
'O art. 84 assegura representar contra superior ao superior subsequente nos casos de abuso, desrespeito e determinações ou atuações irregulares. O art. 97 exige dos superiores exemplo, justiça, zelo pelo material e fiscalização. Não atribua automaticamente a todas as faltas a pena máxima.'
],'O capitão organiza a equipe, mas não ganha autorização para agredir um colega. Existe autoridade e também limite. No serviço público, a representação e a defesa seguem regras legais, não uma discussão de quadra.','A lista de penalidades da GCM não deve ser substituída pela lista de outro município ou da Polícia Militar.','Quais são as quatro penalidades do art. 82?','Advertência verbal, advertência escrita, suspensão e demissão.','uzv-IYyfCck','Complemento nacional: controle e código de conduta'),
a(9,'Servidor: dever, proibição e responsabilidade','servidor','LC 01/2002 • capítulos de deveres, proibições, responsabilidades e penalidades',local1,[
'Dever é comportamento exigido; proibição é comportamento vedado; responsabilidade é a consequência jurídica atribuída por uma conduta. Use essas três categorias para organizar a leitura do Estatuto municipal. Não importe números de artigos ou prazos da Lei federal 8.112: ela não é o estatuto de Mauá.',
'Na prática de estudo, “zelar pelo material público” ilustra dever; “usar o cargo para vantagem particular” ilustra conduta incompatível com a função. Para a questão literal, procure o item correspondente no texto local e anote a formulação exata.',
'Abra o PDF oficial e localize os capítulos cobrados pelo edital. Faça uma tabela com cinco deveres, cinco proibições e as penalidades, anotando artigo e hipótese. Esta aula fornece o método e os conceitos; o PDF digitalizado exige consulta direta e não foi integralmente consolidado aqui. Inclua a LC 60/2026 ao conferir alterações do art. 122.'
],'O clube exige presença e cuidado com o uniforme; proíbe usar recursos do time para benefício pessoal; apura a conduta antes da sanção. No serviço público, cada consequência depende do texto aplicável e de procedimento.','Exemplo didático não substitui a redação legal. Não presuma que as penas e os prazos federais valem em Mauá.','Como você confere se uma penalidade está certa numa questão local?','Identificando a lei municipal, o artigo vigente, a conduta e a hipótese de aplicação — sem transportar regra federal.','uzv-IYyfCck','Complemento: conduta da Guarda; leitura local obrigatória'),
a(10,'Maria da Penha: reconhecer e proteger','maria','Lei 11.340 • arts. 5º a 7º e 18 a 24; Lei 15.384/2026',sources.maria,[
'A lei trata da violência doméstica e familiar contra a mulher nos contextos legais, incluindo relação íntima de afeto, independentemente de coabitação. Não reduza o tema a lesão física.',
'Diferencie violência física, psicológica, sexual, patrimonial e moral. A redação de 2026 também inclui violência vicária: atingir pessoa vinculada à mulher, nos termos do inciso VI, para atingi-la. Reter documentos ilustra violência patrimonial; controlar e humilhar pode caracterizar psicológica; calúnia, difamação ou injúria, moral.',
'Medidas protetivas podem envolver afastamento, restrição de contato e aproximação, suspensão de posse ou restrição de porte de arma e outras providências legais. Não dependem necessariamente de boletim de ocorrência, inquérito ou ação, conforme art. 19. Persistem enquanto houver risco. Leia as hipóteses e autoridades competentes: o agente não inventa medida por conta própria.'
],'Uma atleta pode ser impedida pelo parceiro de ir ao treino por controle e ameaça, mesmo sem agressão física. O exemplo serve para reconhecer violência psicológica, não para banalizar a situação como briga esportiva.','Vídeos antigos podem listar somente cinco formas. A violência vicária foi incluída em abril de 2026, antes deste edital.','Reter os documentos de uma mulher para controlá-la se relaciona a qual forma?','Patrimonial; conforme o caso, outras formas também podem coexistir.','rucJGwqYHhs','Lei Maria da Penha para Guarda Municipal'),
a(11,'Primeiro jogo-treino: medir e corrigir','guardas','Revisão do que estudou + diagnóstico dos próximos assuntos',sources.maua,[
'Hoje faça 40 questões autorais, no formato de distribuição de Mauá. Reserve até 90 minutos para responder e 30 para corrigir. Alguns assuntos ainda não foram estudados: use os erros para localizar lacunas, não como previsão de classificação.',
'Na correção, registre o motivo: não conhecia a regra, confundi uma palavra, interpretei mal ou errei a conta. Uma frase com a regra correta vale mais que copiar toda a explicação.',
'Seu objetivo de treino é aumentar a pontuação e diminuir erros repetidos. 50 pontos é piso de habilitação, não garantia de convocação. A meta de 80/100 da central é apenas uma referência pessoal de estudo.'
],'Treino de saque mostra onde a bola está saindo. O erro tem utilidade quando você ajusta o movimento; repetir sem corrigir reforça o problema.','O banco é autoral e finito; repetir questões pode elevar a nota por familiaridade.','Quais foram seus três erros mais importantes?','Volte ao artigo ou regra de cada erro e explique em voz alta como resolver uma situação diferente.','aCMt7tDLajY','Complemento: simulado comentado de Português IBAM','simulado'),
a(12,'ECA: proteção e ato infracional','eca','ECA • arts. 1º a 6º, direitos e prevenção; 98 a 112 e 121 a 125',sources.eca,[
'Criança é pessoa com menos de 12 anos; adolescente, de 12 a menos de 18. O ECA trabalha com proteção integral e prioridade. Família, comunidade, sociedade e poder público compartilham deveres de proteção.',
'Ato infracional é conduta descrita como crime ou contravenção penal. Quando praticado por criança, aplicam-se medidas de proteção. Ao adolescente podem ser aplicadas medidas socioeducativas previstas em lei, observadas garantias e circunstâncias.',
'A privação de liberdade do adolescente depende de flagrante de ato infracional ou ordem escrita e fundamentada da autoridade judiciária competente. Internação não é resposta automática: obedece a brevidade, excepcionalidade e respeito à condição de desenvolvimento. Proteção inclui saúde, educação, convivência familiar, dignidade e prevenção de ameaças.'
],'Em uma escolinha, o tratamento precisa considerar a fase de desenvolvimento. Um aluno de 11 anos e outro de 16 têm a mesma dignidade, mas o ECA distingue respostas legais por idade.','Criança não recebe medida socioeducativa por ato infracional; recebe medidas de proteção.','Quem tem 12 anos completos é criança ou adolescente?','Adolescente para o ECA.','1MGznw8FQyA','ECA para Guarda Municipal • aula 01'),
a(13,'Flagrante: o que aconteceu e quando?','flagrante','CPP • arts. 301 a 310',sources.cpp,[
'Qualquer pessoa pode prender em flagrante; autoridades policiais e seus agentes devem fazê-lo. O art. 302 inclui quem está cometendo, acaba de cometer, é perseguido logo após nas condições legais ou é encontrado logo depois com elementos que façam presumir autoria.',
'Não existe um prazo genérico de “24 horas para prender em flagrante”. Tempo, continuidade da perseguição e circunstâncias precisam se enquadrar na lei. Nas infrações permanentes, o flagrante persiste enquanto durar a permanência.',
'A prisão deve ser comunicada imediatamente ao juiz competente, ao Ministério Público e à família ou pessoa indicada. O auto deve ser encaminhado em até 24 horas, com as demais exigências do art. 306. O juiz controla a legalidade e decide entre as providências legais do art. 310. Prender em flagrante não é condenar.'
],'No jogo, presenciar a infração é diferente de ouvir um boato muito depois. No processo penal, porém, as hipóteses são jurídicas: perseguição e encontro de vestígios podem configurar flagrante, mesmo sem ter visto o começo.','As 24 horas de comunicação formal do auto não são uma autorização para prender qualquer suspeito até esse prazo.','Qual a diferença entre poder e dever no art. 301?','Qualquer pessoa pode; autoridades policiais e seus agentes devem prender quem esteja em flagrante.','SzreBgHZryc','Prisão em flagrante • espécies'),
a(14,'Cadeia de custódia: a história do vestígio','custodia','CPP • arts. 158-A a 158-F',sources.cpp,[
'Cadeia de custódia documenta a história cronológica do vestígio: quem encontrou, preservou, coletou, transportou e recebeu. Serve à integridade e rastreabilidade, desde o reconhecimento até o descarte.',
'As etapas legais são reconhecimento, isolamento, fixação, coleta, acondicionamento, transporte, recebimento, processamento, armazenamento e descarte. Fixação é descrição detalhada, inclusive por imagens; não significa colar o objeto no chão.',
'Acondicionamento individualizado, identificação e lacres reduzem mistura e contaminação. A coleta é realizada preferencialmente por perito oficial. Não remova vestígios nem entre em local isolado antes da liberação legal. Registre a transferência e preserve a situação conforme as atribuições.'
],'Imagine uma bola autografada usada como evidência: sem registro de quem guardou e entregou, como saber que continua sendo a mesma? A lei exige uma história documentada, não confiança informal entre colegas.','Não confunda fixação com coleta nem armazenamento com descarte.','Por que um lacre e um registro de entrega ajudam?','Permitem verificar integridade e rastrear quem teve contato com o vestígio.','SzreBgHZryc','Complemento: flagrante; cadeia de custódia está no resumo e no CPP'),
a(15,'Furto, roubo, lesão e ameaça','penal','Código Penal • arts. 129, 147, 155 e 157',sources.cp,[
'Furto é subtrair coisa alheia móvel. Roubo envolve subtração com violência, grave ameaça ou redução da capacidade de resistência, nas hipóteses do tipo. Não é o valor do objeto que separa furto de roubo.',
'Lesão corporal atinge a integridade corporal ou a saúde de outra pessoa. Ameaça envolve promessa de mal injusto e grave por palavra, escrito, gesto ou outro meio simbólico. Diferencie a conduta, o resultado e o contexto.',
'Estude primeiro os elementos, depois penas e qualificadoras na redação aplicável até o edital. Uma mesma narrativa pode envolver mais de um crime, mas a questão costuma indicar qual conduta você deve classificar. Leia o comando antes de escolher.'
],'Pegar escondido o celular de um jogador na arquibancada ilustra furto; exigir o celular sob grave ameaça ilustra roubo. A analogia não cobre todas as modalidades e exceções.','“Sem arma” não significa “sem roubo”: grave ameaça pode existir sem arma.','Qual elemento do exemplo transforma a subtração em roubo?','A violência ou a grave ameaça, conforme a hipótese legal.','gdciCK3xqEw','Revisão de Direito Penal para GCM • selecione os crimes do edital'),
a(16,'Dano, resistência e desobediência','penalextra','Código Penal • arts. 163, 329 e 330',sources.cp,[
'Dano envolve destruir, inutilizar ou deteriorar coisa alheia. Não exige levar o objeto embora. No furto, o núcleo é subtrair; no dano, atingir a integridade ou utilidade da coisa.',
'Resistência envolve opor-se à execução de ato legal mediante violência ou ameaça a funcionário competente ou a quem lhe preste auxílio. Desobediência envolve descumprir ordem legal de funcionário público. Confira os elementos: ato ou ordem precisam ser legais.',
'Não classifique automaticamente qualquer reclamação como resistência. Falar de forma crítica não é, por si só, violência ou ameaça. Questões podem trocar o verbo ou omitir um elemento essencial do tipo penal.'
],'Destruir a rede de um ginásio é diferente de furtá-la. E questionar uma decisão não equivale automaticamente a ameaçar quem a executa. A classificação exige fatos e elementos legais.','O edital de Mauá não autoriza estudar todos os crimes do Código Penal com o mesmo peso: concentre-se nos sete indicados.','Qual a diferença central entre resistência e desobediência?','Resistência exige violência ou ameaça na oposição ao ato legal; desobediência não tem esse elemento no tipo.','gdciCK3xqEw','Revisão de Penal • dano, resistência e desobediência'),
a(17,'Abuso: poder tem finalidade e limite','abuso','Lei 13.869/2019 • arts. 1º a 8º e tipos penais',sources.abuso,[
'Agente público, servidor ou não, pode ser sujeito ativo. A lei exige finalidade específica: prejudicar outra pessoa, beneficiar a si ou terceiro, mero capricho ou satisfação pessoal. Erro isolado não basta automaticamente.',
'Divergência de interpretação da lei ou de avaliação de fatos e provas não configura abuso de autoridade por si só. Os crimes são de ação penal pública incondicionada. Responsabilidades civil, administrativa e criminal têm regras próprias.',
'Leia os tipos em blocos: prisão ilegal e constrangimentos; ingresso em imóvel; obtenção e uso de prova ilícita; investigação sem justa causa e divulgação indevida. A perda do cargo e a inabilitação do art. 4º exigem reincidência em abuso e declaração motivada; não são automáticas.'
],'Um árbitro que erra uma interpretação não é igual a alguém que usa a posição deliberadamente para prejudicar um atleta. A comparação explica a finalidade, mas árbitro de jogo não vira agente público por essa analogia.','O simples resultado desagradável não prova a finalidade específica nem o preenchimento de um tipo penal.','Toda interpretação jurídica errada é abuso?','Não. É preciso verificar os elementos do tipo e a finalidade específica exigida pela lei.','BtzCYT-0WjE','Questões: Maria da Penha e abuso de autoridade'),
a(18,'Segundo simulado: transformar erro em regra','flagrante','40 questões + revisão do caderno de erros',sources.maua,[
'Responda sem consultar. Depois, confira sua pontuação ponderada: cada acerto em Específicos vale quatro; nas outras matérias, um. Compare a compreensão, não apenas a nota, pois o banco pode repetir questões.',
'Escolha três erros de legislação e leia o dispositivo correspondente. Faça uma nova frase de exemplo para cada um. Se errou “pode” versus “deve”, escreva os dois sujeitos e os verbos corretos.',
'Na semana seguinte entram força, trânsito, atuação e socorros. Se há matéria atrasada, priorize a próxima aula de Específicos e uma revisão curta; não tente cumprir várias horas de uma vez.'
],'É a pausa entre sets: observe onde perde pontos e ajuste a estratégia. Não abandone a partida por um set ruim.','Não use o mínimo de 50 pontos como alvo confortável; a convocação também depende da classificação.','Qual palavra mudou a resposta em um dos seus erros?','Identifique a palavra, explique sua consequência e teste a regra num caso novo.','aCMt7tDLajY','Complemento de Português IBAM','simulado'),
a(19,'Uso da força: necessário e proporcional','forca','Lei 13.060/2014 • leitura integral',sources.forca,[
'A lei orienta legalidade, necessidade, razoabilidade e proporcionalidade. Deve-se priorizar instrumento de menor potencial ofensivo quando isso não colocar em risco a integridade física ou psíquica dos agentes, nos termos legais.',
'Menor potencial ofensivo significa baixa probabilidade de morte ou lesão permanente, não risco zero. A lei considera ilegítimo usar arma de fogo contra pessoa em fuga desarmada ou sem risco imediato de morte ou lesão; também disciplina o veículo que rompe bloqueio e a exceção de risco.',
'Havendo ferimentos decorrentes do uso da força, devem ser assegurados assistência e socorro médico imediatos e comunicação à família ou pessoa indicada. Capacitação e fornecimento de instrumentos adequados são deveres previstos na lei.'
],'No vôlei, você ajusta a força e o movimento à situação. Na atuação pública a escolha é muito mais séria: não se trata de “ganhar a disputa”, mas de atingir uma finalidade legal com necessidade e proporcionalidade.','Fuga, por si só, não justifica disparo. Instrumento de menor potencial ofensivo não é inofensivo.','Após ferimento provocado pelo uso da força, basta registrar a ocorrência?','Não. Há dever de assistência e socorro médico imediato e comunicação prevista na lei.','AMMqFUEf1N8','Lei 13.060 • uso da força e instrumentos de menor potencial ofensivo'),
a(20,'CTB: circulação, pedestre e sinalização','ctb','CTB • arts. 26 a 67, 68 a 71 e 80 a 90',sources.ctb,[
'O condutor deve manter domínio do veículo e atenção. A circulação é pelo lado direito, salvo exceções sinalizadas; ultrapassagem exige condições seguras e segue as regras legais. Veículos maiores devem zelar pelos menores e todos pela incolumidade dos pedestres.',
'Em interseção não sinalizada, identifique as hipóteses: rodovia, rotatória e, nos demais casos, preferência de quem vem pela direita. Não aplique “direita sempre” antes de conferir se é uma situação especial.',
'A ordem do agente prevalece sobre normas e sinais; semáforo prevalece sobre os demais sinais; sinais prevalecem sobre as normas gerais. Pedestre que não concluiu a travessia deve ser protegido nas condições do art. 70. Leia também as regras para ciclistas e veículos não motorizados.'
],'Você dirige seu Ka e chega a um semáforo verde, mas o agente manda parar. A ordem do agente prevalece. É uma situação concreta para lembrar a ordem do art. 89.','O tamanho do veículo não dá preferência. Mais capacidade de causar dano implica maior cuidado.','O que prevalece: ordem do agente ou sinal verde?','A ordem do agente.','iC1TxaMXv0c','CTB • normas gerais de circulação e conduta'),
a(21,'CTB: infração, pena e medida','ctb2','CTB • infrações; arts. 256, 269 e 280',sources.ctb,[
'Infração é o descumprimento da norma; penalidade é a sanção; medida administrativa é uma providência prevista para a situação. Multa é penalidade. Retenção e remoção são medidas administrativas distintas.',
'Estude as classificações leve, média, grave e gravíssima e os elementos das infrações. Não conclua a gravidade só pela sua impressão. Compare a descrição do comportamento com a previsão legal.',
'Autuação exige elementos do auto e atuação do agente competente. O agente não pode inventar penalidade. Leia as hipóteses de advertência, multa, suspensão e cassação e distinga retenção para regularização de remoção. Não confunda apreensão, termo de normas antigas, com a lista atual de penalidades.'
],'No campeonato, a falta é uma conduta; a sanção é sua consequência; reorganizar a quadra é uma providência. No trânsito, cada categoria tem nome e previsão próprios.','Não troque “retenção” por “suspensão da CNH”: uma é medida, a outra penalidade.','Classifique multa e remoção.','Multa: penalidade. Remoção: medida administrativa.','EOi8AV-NxTk','Complemento de CTB • leia também as seções de penalidades e medidas'),
a(22,'Prevenir conflito e atender bem','operacional','Lei 13.022 • art. 5º; LC 62 • art. 52-A',local62,[
'Atuação preventiva começa por observar riscos, conhecer o serviço e comunicar irregularidades. Controle de acesso precisa seguir regras do local, registrar o necessário e orientar o público sem discriminação.',
'Em conflito, use comunicação clara, escuta e linguagem respeitosa, mantenha segurança e acione apoio quando necessário. Mediar não significa obrigar vítima a aceitar acordo nem ignorar um flagrante.',
'Integração é cooperar dentro das atribuições: Guarda, saúde, assistência social, defesa civil e demais órgãos têm papéis próprios. A lei local exige urbanidade mesmo quando a outra pessoa age de forma diferente, além de comunicar a chefia e colaborar em calamidades.'
],'Numa discussão entre atletas, falar um de cada vez e esclarecer o problema pode reduzir tensão. Na rua, acrescente avaliação de risco, competência legal e encaminhamento adequado; não trate violência como simples desentendimento.','Atender com educação não exige permitir acesso indevido a uma área restrita.','Como negar acesso sem humilhar a pessoa?','Explique a regra de forma objetiva, indique a alternativa permitida, mantenha segurança e acione o responsável quando necessário.','uzv-IYyfCck','Complemento: competências preventivas das Guardas'),
a(23,'Socorros: reconhecer e pedir ajuda','socorros','SAMU • segurança da cena, acionamento e PCR',aid,[
'Antes de se aproximar, verifique riscos: trânsito, fogo, eletricidade, violência e estruturas instáveis. Não crie uma segunda vítima. Acione SAMU 192 para urgência médica; Corpo de Bombeiros 193 para incêndio e resgate.',
'Informe local exato, referência, o que aconteceu, número de vítimas e estado observado. Siga as orientações do atendente. Pessoa que não responde e não respira normalmente pode estar em parada: peça ajuda, solicite DEA e siga orientação para atendimento imediato.',
'Para estudo de PCR em adulto, revise compressões de 100 a 120 por minuto, profundidade de cerca de 5 a 6 cm, retorno do tórax e interrupções mínimas com material oficial e instrutor. O DEA orienta o uso. Esta aula é revisão de prova, não certificação prática; não treine compressões em colegas.'
],'Um atleta cai e não responde. Em vez de uma roda de pessoas dando palpites, alguém identifica o local e chama 192, outra pessoa busca o DEA. Organização e orientação especializada importam.','Respiração agônica não é respiração normal. Não espere a pessoa “melhorar sozinha” para pedir ajuda.','Quais quatro informações você passa ao 192?','Local, o que ocorreu, quantidade de vítimas e estado aparente delas.','xk7Ze3QGGps','Noções de primeiros socorros para GCM'),
a(24,'Engasgo, hemorragia, queimadura e incêndio','socorros2','Manual de primeiros socorros + material oficial do SAMU','https://www.prefeitura.sp.gov.br/cidade/secretarias/upload/saude/MANUAL_PRIMEIROS_SOCORROS_PARA_LEIGOS.pdf',[
'Engasgo: diferencie tosse eficaz de obstrução grave com incapacidade de falar, tossir ou respirar. Acione ajuda e siga o protocolo adequado à idade e condição. Não faça varredura cega com o dedo nem pratique manobras em colegas.',
'Hemorragia externa exige controle rápido, proteção contra contato com sangue e pressão direta quando indicada. Queimaduras não recebem gelo, pasta de dente ou receitas caseiras. Convulsão: afaste objetos perigosos, proteja a cabeça, não contenha à força nem coloque objetos na boca; acione ajuda e observe o tempo. Desmaio não autoriza dar líquido a quem está inconsciente.',
'Prevenção de incêndio envolve manter saídas livres e identificar riscos. Ao perceber fogo ou fumaça, alerte, evacue por rota segura e chame 193. Não use elevador, não retorne para buscar objetos e não se exponha para combater um incêndio sem capacitação. Revise classes de fogo e agentes extintores em material do Corpo de Bombeiros.'
],'No ginásio, mochilas bloqueando a saída atrapalham a evacuação. Retirá-las antes do evento é prevenção. Durante uma emergência, preservar pessoas vem antes de salvar o placar ou material.','Não coloque colher na boca durante convulsão. Não dê água a pessoa inconsciente.','O que vem primeiro ao chegar a uma vítima perto de um fio caído?','Garantir segurança da cena, manter distância do risco e acionar os serviços competentes.','xk7Ze3QGGps','Primeiros socorros • complemente os tópicos na fonte oficial'),
a(25,'Simulado geral: ensaio de prova','maria','40 questões • pesos de Mauá',sources.maua,[
'Agora todos os grandes blocos de Específicos já apareceram. Faça um simulado sem consulta. Use 90 minutos mais 30 de correção como treino compacto; se puder, reserve em outra ocasião as 3h30 reais, incluindo cartão-resposta.',
'Separe erros por assunto. Seu próximo estudo começa pelos erros de maior peso e pelos repetidos. Evite refazer imediatamente a mesma questão só para subir a nota: explique a regra antes.',
'Confira inscrição, pagamento, categoria A+B e convocação prevista para 23/10. O site não consulta sua inscrição nem atualiza o edital automaticamente. Entre na fonte oficial para confirmar local e horário.'
],'É o amistoso antes do campeonato: simule concentração e decisões, depois converse sobre o que corrigir.','Este simulado não é prova oficial nem estimativa confiável de posição na classificação.','Quais assuntos precisam de revisão nos últimos dias?','Priorize os erros de Específicos; depois, os básicos em que você consegue recuperar pontos.','aCMt7tDLajY','Complemento de questões IBAM em Português','simulado'),
a(26,'Português: entender antes de decorar','texto','Interpretação, gramática e reescrita • Anexo II',sources.maua,[
'Informação explícita está escrita; inferência tem apoio em pistas; extrapolação acrescenta algo sem apoio. Em “a equipe treinou, mas perdeu”, existe contraste, não relação de causa obrigatória.',
'Encontre o núcleo do sujeito para concordar: “Os jogadores da equipe chegaram”. Haver no sentido de existir é impessoal: “Há vagas”. Existir concorda: “Existem vagas”. Fazer indicando tempo também fica no singular.',
'Crase pode reunir preposição a e artigo a: “dirigiu-se à quadra”. Antes de verbo não ocorre essa fusão. Não separe sujeito e verbo por vírgula. Na reescrita, verifique sentido, tempo verbal, conectivo e concordância. Revise classes, acentos, regência e colocação pronominal pelos microtreinos do mês.'
],'“O time perdeu alguns jogos” não significa “perdeu todos”. Essa troca de quantidade é uma extrapolação comum em interpretação.','Uma frase pode estar gramaticalmente correta e ainda mudar o sentido do texto.','Corrija: houveram falhas; faziam dois meses; existe vagas.','Houve falhas; fazia dois meses; existem vagas.','AmpS4BN4t_o','Desvendando a banca IBAM • Português'),
a(27,'Matemática: montar antes de calcular','percent','Operações, proporção, medidas, equações e lógica',sources.maua,[
'Transforme percentuais em fatores: desconto de 20% é ×0,80; aumento de 10% é ×1,10. Aumentar e depois reduzir 10% não volta ao início: 100 × 1,10 × 0,90 = 99.',
'Regra de três exige identificar a relação. Mais pessoas no mesmo ritmo reduzem o tempo de um trabalho fixo. Média simples = soma ÷ quantidade. Equação: aplique a mesma operação aos dois lados. Converta as unidades antes.',
'A negação de “todos treinam” é “pelo menos um não treina”. Negar “P e Q” dá “não P ou não Q”; negar “P ou Q” dá “não P e não Q”. “Se P, então Q” só é falsa quando P é verdadeira e Q falsa; equivale a “não P ou Q”.'
],'Você acerta 18 de 30 saques: 18÷30 = 0,60 = 60%. Se a questão pedir erros, são 12÷30 = 40%. O comando decide qual conta interessa.','Percentual sempre tem uma base. Confira “de quê?” antes de calcular.','Quatro atletas montam a quadra em seis minutos. Seis, no mesmo ritmo, levam quanto?','Quatro minutos: 4×6 = 24 atleta-minutos; 24÷6 = 4.','i5uCyUaAeHE','Porcentagem • teoria e questões para concursos'),
a(28,'Informática: do arquivo ao golpe digital','excel','Arquivos, Word, Excel, navegador, e-mail e segurança',sources.maua,[
'Copiar preserva o original; mover muda sua localização. Atalho aponta para um recurso, não é o próprio arquivo. No Word, diferencie margem da página, recuo do parágrafo, alinhamento, cabeçalho e rodapé; localizar não é substituir.',
'No Excel, =SOMA(A1:A3) soma um intervalo; =MÉDIA(A1:A3) calcula a média. MÁXIMO e MÍNIMO retornam extremos; CONT.NÚM conta células numéricas. $A$1 fixa coluna e linha. Filtrar não apaga dados; classificar muda a ordem.',
'No e-mail, Cc exibe destinatários e Cco os oculta dos demais destinatários. Phishing tenta enganar; ransomware pode bloquear ou cifrar dados e exigir resgate. Use senhas únicas, autenticação em múltiplos fatores e backups. Navegação privada não torna você invisível na internet.'
],'Uma planilha de saques tem 10, 20 e 30 acertos. SOMA dá 60; MÉDIA dá 20; MÁXIMO dá 30; CONT.NÚM dá 3. Mesmos dados, perguntas diferentes.','Sincronizar não é garantir backup: uma exclusão pode se propagar.','Qual fórmula calcula a média de B2 até B6?','=MÉDIA(B2:B6).','kcoWtTA_tGE','Excel para concursos • SOMA, MÉDIA, MÁXIMO e MÍNIMO'),
a(29,'Mauá: revisão das regras locais','local3','LC 19 + LC 62/2026 + capítulos da LC 01/2002',local62,[
'Monte de memória um quadro: instituição civil; ingresso na 3ª Classe; CNH A+B; bolsa de 50%; curso com média superior a 70%; estágio probatório de três anos. Só depois confira a fonte.',
'Revise as atribuições da 3ª Classe: proteção, rondas e acesso; condução de veículos; disciplina e urbanidade; comunicação e colaboração. Para disciplina, recorde as quatro penalidades do art. 82 e o direito de representação do art. 84.',
'Volte à tabela que fez da LC 01/2002. Se não fez, use este bloco para ler os capítulos cobrados. Não gaste a reta final decorando artigo revogado: confronte a redação de 2014 com a alteração de 2026.'
],'Antes do jogo, o time revisa posições e responsabilidades. Aqui, você revisa quem faz o quê e qual regra vale hoje.','Não responda com a antiga classe de entrada nem com a antiga idade máxima.','A bolsa do aluno é de 100%? A média de aprovação é exatamente 70%?','Não. A LC 62 prevê bolsa de 50% e média superior a 70%.','uzv-IYyfCck','Revisão nacional opcional; hoje priorize as leis de Mauá'),
a(30,'Revisão final: diferenças que dão pontos','abuso','Caderno de erros + leis dos temas errados',sources.maua,[
'Faça pares: princípio/competência; corregedoria/ouvidoria; pode/deve; fundamento/objetivo; criança/adolescente; furto/roubo; resistência/desobediência; penalidade/medida; regra/exceção.',
'Em cada par, explique a diferença e um exemplo. Confira três erros antigos de maior peso. Se acertar por lembrar a alternativa, mude o contexto e tente explicar novamente.',
'Faça um treino curto de dez questões de Específicos. Não abra uma maratona de assuntos novos à noite. Separe documento, caneta, trajeto e horário conforme a convocação oficial.'
],'É o treino de fundamento antes da decisão: corrigir uma falha recorrente pode render mais que tentar aprender uma jogada complicada do zero.','Este plano organiza o esforço, mas não garante aprovação nem esgota todas as hipóteses das leis.','Qual confusão você já consegue explicar sem consultar?','Escolha um par, dê um exemplo e cite a regra que decidiu a questão.','AMMqFUEf1N8','Revisão opcional de uso da força'),
a(31,'Véspera: revisar pouco, chegar preparado','guardas','Convocação oficial + suas anotações',official,[
'Hoje são 20 minutos. Releia seu resumo de diferenças e cinco erros que já corrigiu. Evite fazer um simulado longo para buscar confiança na última hora.',
'Confirme local e horário na convocação. Confira documento aceito, caneta e demais exigências do edital. Planeje a saída para chegar com antecedência; a prova está prevista para 01/11 e dura 3h30, incluindo a folha de respostas.',
'Na prova, leia o comando e destaque mentalmente “correta”, “incorreta”, “exceto”. Garanta as fáceis, volte às difíceis e reserve tempo para o cartão. A prova objetiva é uma etapa; TAF e demais avaliações continuam importantes.'
],'Antes da final, descanso e equipamento pronto ajudam mais que um treino exaustivo de última hora.','Não confie só num aviso por e-mail: confira o canal oficial.','Documento, trajeto e horário estão conferidos?','Marque a aula concluída depois de revisar e organizar os itens da prova.','','','vespera')
];
const extras=[
'Português • “O time treinou, mas perdeu.” Mas indica oposição. Trocar por portanto muda o sentido.',
'Matemática • 3/4 = 0,75 = 75%. Em 20 saques, 75% são 15 acertos.',
'Informática • Copiar cria outra instância; mover muda o local. Excluir um atalho não equivale a excluir o arquivo de destino.',
'Português • “Os atletas da equipe chegaram.” Núcleo do sujeito: atletas. Da equipe não muda o plural.',
'Matemática • 2,5 horas = 150 minutos. 1,5 km = 1.500 m. 1 m² = 10.000 cm².',
'Português • Substantivo nomeia; adjetivo caracteriza; verbo indica ação/estado; advérbio modifica verbo, adjetivo ou advérbio. “Treinou muito”: muito modifica treinou.',
'Informática • Margem é espaço da página; recuo afasta o parágrafo da margem. Cabeçalho se situa na região superior.',
'Português • Concordância na gramática: “há vagas”, “existem vagas”, “faz dois anos”.',
'Matemática • 3x+6=21 → 3x=15 → x=5. Confira substituindo x na equação.',
'Português • “Dirigiu-se à quadra” / “ao ginásio”. Antes de estudar, verbo, não há artigo: “começou a estudar”.',
'Correção • Escolha um erro de Português e um de Matemática. Escreva a regra e faça um exemplo diferente.',
'Informática • =SOMA(A1:A3) com 2,4,6 dá 12; =MÉDIA(A1:A3) dá 4; =CONT.NÚM(A1:A3) dá 3.',
'Português • Não separe sujeito e verbo: “A equipe chegou”. Vocativo pode ser separado: “Vitor, revise a lei”.',
'Matemática • 100 com dois aumentos de 10% vira 121, não 120. Os fatores são multiplicados.',
'Português • “Embora cansado, treinou”: concessão. “Treinou porque queria melhorar”: causa. “Treinou para melhorar”: finalidade.',
'Informática • A referência $A$1 fixa linha e coluna. A$1 fixa só a linha; $A1 fixa só a coluna.',
'Português • A negação atrai pronome na norma-padrão: “não me avisou”. Observe o termo atrativo antes de escolher a colocação.',
'Correção • Diga em voz alta a regra de três erros. Amanhã, recupere as mesmas regras sem olhar.',
'Matemática • 6 atletas com 2 camisetas cada = 12 camisetas. 12 divididas igualmente por 4 atletas = 3 para cada um.',
'Português • Oxítonas como café; paroxítonas como fácil; proparoxítonas como público. Todas as proparoxítonas são acentuadas. Revise as regras e exceções.',
'Informática • Cc: cópia com destinatários visíveis. Cco: cópia oculta. Download traz um arquivo para seu dispositivo; upload envia.',
'Matemática • A negação de “P e Q” é “não P ou não Q”. A negação de “todos” é “pelo menos um não”.',
'Português • Futuro indica ação posterior; pretérito perfeito, ação concluída; imperfeito, hábito/continuidade no passado. “Treinava” não equivale sempre a “treinou”.',
'Informática • Phishing engana para obter dados/acesso; ransomware pode cifrar dados. Backup deve permitir recuperação mesmo se a origem falhar.',
'Correção • Compare pontos de Específicos e Básicos separadamente. Quantifique onde perdeu mais.',
'Português • Assistir, no sentido de ver, pede a na norma-padrão: assistir ao jogo. Prefere-se uma coisa a outra. Revise regência, coordenação, subordinação e reescrita.',
'Matemática • Sequência 2,4,8,16 segue ×2. “Se P então Q” equivale a “não P ou Q”. Negação: P e não Q.',
'Informática • Filtrar oculta linhas fora do critério; classificar ordena. Um favorito guarda referência de página; histórico registra navegações.',
'Português • “O bloqueio foi uma muralha” é figurado. Sinônimo depende do contexto; substituir uma palavra pode alterar o sentido.',
'Matemática • Média de 10,20,30 = 20. Frações: 1/2+1/4 = 3/4. Em expressões, respeite parênteses e precedência.',
'Logística • Consulte a convocação oficial. Prepare os itens permitidos e organize o horário de saída.'
];
baseAulas.forEach((x,i)=>x.extra=extras[i]);
const groups=[[1],[2],[3],[4],[5],[6,7],[11],[8,9],[10],[12],[13,14],[15],[16],[18],[17],[19],[20,21],[22],[23],[24],[25],[26],[27],[28],[29],[30],[31]];
const mergedTitles:Record<number,string>={6:'Mauá: estrutura, ingresso e formação',8:'Mauá: disciplina e deveres do servidor',13:'Flagrante e cadeia de custódia',20:'Trânsito: circulação, infrações e medidas'};
export const aulas:Aula[]=groups.map((group,i)=>{
 const rows=group.map(d=>baseAulas[d-1]), first=rows[0];
 return {...first,originalDay:first.day,day:i+1,date:`2026-10-${String(i+5).padStart(2,'0')}`,title:rows.length>1?mergedTitles[first.day]:first.title,topics:rows.map(r=>r.topic),reading:rows.map(r=>r.reading).join(' + '),parts:rows.flatMap(r=>r.parts),trap:rows.map(r=>r.trap).join(' '),recall:rows.map(r=>r.recall).join(' '),answer:rows.map(r=>r.answer).join(' '),moreSources:rows.slice(1).map(r=>({url:r.url,label:r.reading})),minutes:first.kind==='simulado'?120:first.kind==='vespera'?20:i<3?30:rows.length>1?60:45};
});

const newRows:[string,string,string,string[],number,string][]=[
['guardas','Legislação','Respeitar a vida é princípio; proteger uma escola municipal é exemplo de:',['Competência','Sanção','Regime militar','Pena criminal'],0,'Princípios orientam como agir; competências descrevem atribuições. Lei 13.022, arts. 3º e 5º.'],
['guardas2','Legislação','Uma guarda com 30 integrantes que utiliza arma de fogo deve ter:',['Só ouvidoria','Corregedoria, pela hipótese de uso de arma','Controle militar obrigatório','Dispensa de controle'],1,'Art. 13: corregedoria nas guardas com mais de 50 servidores e em todas as que utilizam arma de fogo.'],
['cf1','Legislação','Qual é fundamento da República, e não objetivo?',['Desenvolvimento nacional','Redução das desigualdades','Dignidade da pessoa humana','Construção de sociedade solidária'],2,'Dignidade está no art. 1º; as demais alternativas remetem ao art. 3º.'],
['cf1','Legislação','A defesa da paz aparece na Constituição como:',['Princípio das relações internacionais','Penalidade disciplinar','Requisito de ingresso na Guarda','Objetivo de uma empresa pública'],0,'Art. 4º: defesa da paz é princípio das relações internacionais do Brasil.'],
['cf144','Legislação','Favorecer um amigo no atendimento público viola especialmente a:',['Publicidade','Impessoalidade','Continuidade','Especialidade'],1,'A Administração deve atender ao interesse público sem favoritismo pessoal. CF, art. 37.'],
['local1','Legislação','A Guarda de Mauá, embora armada e organizada em hierarquia, tem caráter:',['Militar federal','Judicial','Civil','Partidário'],2,'LC 19/2014, art. 1º: caráter civil.'],
['local1','Legislação','Mediação de conflitos e patrulhamento comunitário são compatíveis com a LC 19?',['Não, nunca','Só fora de Mauá','Apenas após condenação','Sim, são previstos no art. 4º'],3,'O art. 4º prevê patrulhamento preventivo e comunitário e mediação de conflitos.'],
['local3','Legislação','A LC 62/2026 estabelece como classe inicial de ingresso:',['3ª Classe','2ª Classe','Classe Especial','Inspetor'],0,'A LC 62 alterou os arts. 35 e 53 da LC 19 para ingresso na 3ª Classe.'],
['local3','Legislação','A bolsa-auxílio do GCM Aluno corresponde a:',['30%','50% do vencimento inicial da 3ª Classe','70%','100%'],1,'LC 62, art. 6º, nova redação do art. 56.'],
['local3','Legislação','Segundo a LC 62, a média exigida no curso de formação é:',['Igual a 50%','Pelo menos 60%','Superior a 70%','Qualquer média positiva'],2,'A lei usa superior a 70%, não simplesmente igual ou superior.'],
['local2','Legislação','Qual NÃO integra a lista do art. 82 da LC 19?',['Advertência verbal','Advertência escrita','Suspensão','Prisão disciplinar militar'],3,'A lista tem advertência verbal, advertência escrita, suspensão e demissão.'],
['local2','Legislação','O art. 84 permite representar contra superior por abuso junto:',['Ao superior subsequente','A qualquer torcedor','Somente à própria pessoa acusada','A ninguém'],0,'Há direito de representação ao superior subsequente nos casos indicados.'],
['servidor','Legislação','Para resolver questão sobre deveres do servidor municipal de Mauá, a referência indicada pelo edital é:',['Somente a Lei 8.112','LC municipal 01/2002 e alterações aplicáveis','Regulamento esportivo','Estatuto de Guarulhos'],1,'É necessário usar o Estatuto municipal indicado, sem importar automaticamente normas federais.'],
['servidor','Legislação','Dever, proibição e penalidade correspondem, respectivamente, a:',['Sanção, obrigação, permissão','Permissão, sanção, obrigação','Conduta exigida, conduta vedada, sanção','Tudo a mesma coisa'],2,'Distinguir essas categorias ajuda a interpretar a norma, mas a aplicação depende do texto vigente.'],
['maria','Legislação','A violência vicária foi incluída na Lei Maria da Penha em 2026. Seu núcleo envolve:',['Apenas dano ao carro','Apenas uma discussão verbal','Qualquer falta esportiva','Violência contra pessoa vinculada à mulher para atingi-la, nos termos legais'],3,'Lei 15.384/2026 incluiu o inciso VI no art. 7º. Não confunda com rol antigo de cinco formas.'],
['eca','Legislação','Uma pessoa com 11 anos que pratica ato infracional está sujeita, pelo ECA, a:',['Medidas de proteção','Internação socioeducativa automaticamente','Pena de adulto','Nenhuma proteção'],0,'Criança: medidas de proteção. ECA, arts. 2º e 105.'],
['custodia','Legislação','Descrição detalhada do vestígio, inclusive por fotografia, corresponde à etapa de:',['Descarte','Fixação','Condenação','Armazenamento definitivo'],1,'CPP art. 158-B: fixação é descrição detalhada do vestígio como encontrado.'],
['penalextra','Legislação','Destruir deliberadamente coisa alheia, na hipótese básica descrita no CP, corresponde a:',['Furto','Roubo','Dano','Desobediência'],2,'Art. 163: destruir, inutilizar ou deteriorar coisa alheia.'],
['penalextra','Legislação','O elemento de violência ou ameaça na oposição à execução de ato legal aparece no crime de:',['Dano','Furto','Desobediência simples','Resistência'],3,'Art. 329. Desobediência, art. 330, não tem esse elemento no tipo.'],
['abuso','Legislação','A perda do cargo prevista no art. 4º da Lei de Abuso é:',['Condicionada à reincidência e declaração motivada','Automática em qualquer erro','Sempre decidida pelo colega','Obrigatória sem sentença'],0,'A lei afasta automatismo e exige as condições do parágrafo único do art. 4º.'],
['forca','Legislação','Menor potencial ofensivo significa:',['Ausência completa de risco','Baixa probabilidade de causar morte ou lesão permanente','Uso livre sem necessidade','Dispensa de capacitação'],1,'Lei 13.060, art. 4º. Baixa probabilidade não equivale a risco zero.'],
['ctb2','Legislação','No CTB, a remoção do veículo é:',['Crime','Princípio constitucional','Medida administrativa','Sinônimo de multa'],2,'CTB art. 269: remoção é medida administrativa. Multa está entre as penalidades do art. 256.'],
['ctb2','Legislação','Qual alternativa é uma penalidade de trânsito?',['Retenção','Remoção','Recolhimento de documento','Multa'],3,'CTB art. 256: multa é penalidade. Não confundir com medidas administrativas.'],
['operacional','Legislação','Pessoa irritada pede acesso a área restrita. A conduta adequada é:',['Orientar com urbanidade e seguir as regras de acesso','Humilhar para impor respeito','Liberar sempre','Abandonar o posto'],0,'LC 62, art. 52-A: controle de acesso e urbanidade convivem.'],
['operacional','Legislação','Atuação integrada significa:',['Substituir todos os órgãos','Cooperar respeitando competências','Ignorar registros','Prometer solução fora da atribuição'],1,'Lei 13.022, art. 5º: articulação e colaboração respeitam as atribuições.'],
['socorros','Legislação','Antes de aproximar-se de vítima em local com fiação caída, deve-se priorizar:',['Gravar vídeo','Remover objetos pessoais','Segurança da cena e acionamento de ajuda','Oferecer líquido'],2,'Material oficial de primeiros socorros: não se torne outra vítima.'],
['socorros','Legislação','Ao ligar para o SAMU 192, é útil informar:',['Só seu nome','Somente a idade','Apenas a profissão','Local, ocorrido, número e estado das vítimas'],3,'As informações ajudam o serviço a orientar e organizar a resposta.'],
['socorros2','Legislação','Durante convulsão, qual atitude deve ser evitada?',['Colocar objeto na boca','Afastar objetos perigosos','Observar o tempo','Acionar ajuda'],0,'Objetos na boca e contenção forçada podem causar lesões.'],
['socorros2','Legislação','Em queimadura, qual conduta é inadequada?',['Buscar atendimento','Aplicar pasta de dente','Não estourar bolhas','Seguir orientação do serviço de saúde'],1,'Receitas caseiras, gelo e pasta de dente não devem ser aplicados. Fonte: SAMU.'],
['logica','Matemática','Negar “Vitor estuda e treina” resulta em:',['Vitor não estuda e não treina','Vitor estuda ou treina','Vitor não estuda ou não treina','Vitor sempre treina'],2,'Lei de De Morgan: a negação de P e Q é não P ou não Q.'],
['medidas','Matemática','18 acertos em 30 saques representam:',['18%','30%','40%','60%'],3,'18÷30=0,6; multiplicando por 100, 60%.'],
['word','Informática','No Word, o recuo de parágrafo e a margem da página:',['São configurações diferentes','São sempre iguais','Apagam o texto','São funções do Excel'],0,'Margens delimitam a área da página; recuos ajustam a posição do parágrafo em relação a elas.'],
['excel','Informática','Filtrar uma tabela normalmente:',['Apaga dados','Oculta linhas que não atendem ao critério','Muda todas as fórmulas','Remove o arquivo'],1,'Filtrar seleciona o que se mostra; não equivale a excluir registros.']
];
const mauTopics=new Set(oldLessons.filter(l=>l.scope!=='Guarulhos').map(l=>l.id));
export const bank:Question[]=[...oldQuestions.filter(q=>mauTopics.has(q.lesson)),...newRows.map((r,i)=>({id:'maua-oct-'+i,lesson:r[0],area:r[1],q:r[2],options:r[3],correct:r[4],why:r[5]}))];
export function dailyQuestions(x:Aula){if(x.kind==='simulado')return mock(x.day);if(x.originalDay===30)return bank.filter(q=>q.area==='Legislação').slice(-12,-2);if(x.originalDay===31)return bank.filter(q=>['guardas','local3','maria'].includes(q.lesson)).slice(-5);return (x.topics||[x.topic]).flatMap(t=>bank.filter(q=>q.lesson===t).slice(-4));}
export function mock(seed:number){const output:Question[]=[];for(const [area,n] of [['Português',10],['Matemática',6],['Informática',4],['Legislação',20]] as [string,number][]){const pool=bank.filter(q=>q.area===area);const offset=seed%pool.length;output.push(...[...pool.slice(offset),...pool.slice(0,offset)].slice(0,n));}return output;}
export const checklist=[['inscricao','Inscrição e pagamento conferidos','Inscrição até 08/10, 23h59; taxa R$74. Confira o vencimento do boleto.'],['cnh','Plano para obter CNH A+B confirmado','Você informou B. O edital exige A e B na comprovação para ingresso. Consulte IBAM/Prefeitura e Detran/CFC sobre o prazo viável.'],['cotas','Modalidade de concorrência conferida','Se optar pela reserva para candidatos negros, confira declaração e procedimento do capítulo específico; não é automático.'],['local','Local e horário da prova conferidos','Convocação prevista para 23/10; prova prevista para 01/11. Confirme no canal oficial.'],['taf','Regras do TAF lidas','Basquete e vôlei ajudam no condicionamento, mas não substituem a técnica e os índices exigidos pelo edital.']];
