const photoData=[
[16,'Externa','Fachada e quintal amplo'],[12,'Externa','Varanda com redes'],[28,'Cozinhas','Área gourmet e churrasqueira'],[25,'Sala','Sala com televisão'],[26,'Cozinhas','Cozinha interna'],[32,'Quartos','Quarto com beliche e cama'],[34,'Quartos','Quarto com cama de casal'],[1,'Banheiros','Banheiro com box e chuveiro'],[13,'Externa','Quintal no fim de tarde'],[30,'Cozinhas','Espaço para refeições'],[33,'Quartos','Outra vista do quarto'],[11,'Externa','Redes na varanda'],[22,'Cozinhas','Bancada da cozinha'],[29,'Sala','Sala e televisão'],[17,'Externa','Varanda coberta'],[31,'Externa','Vista do espaço externo'],[0,'Externa','Entrada e estacionamento'],[2,'Externa','Quintal e varanda'],[3,'Cozinhas','Vista da cozinha'],[4,'Cozinhas','Cozinha da varanda'],[5,'Sala','Sofá da sala'],[6,'Sala','Detalhes da sala'],[7,'Sala','Sala de estar'],[8,'Externa','Quintal visto da rede'],[9,'Sala','Sala com TV'],[10,'Externa','Varanda e redes'],[14,'Externa','Acesso lateral'],[15,'Externa','Espaço para carros'],[18,'Externa','Passagem lateral da casa'],[19,'Externa','Corredor lateral'],[20,'Externa','Varanda da casa'],[21,'Externa','Área externa nos fundos'],[23,'Cozinhas','Outra vista da cozinha']
];
const path=i=>`assets/casa-${String(i).padStart(2,'0')}.webp`;let filter='Todos',expanded=false,current=0,shown=[];const gallery=document.querySelector('#gallery'),more=document.querySelector('#more'),box=document.querySelector('#lightbox');
function renderGallery(){shown=photoData.filter(p=>filter==='Todos'||p[1]===filter);const visible=expanded?shown:shown.slice(0,9);gallery.replaceChildren(...visible.map((p,i)=>{let b=document.createElement('button');b.type='button';b.setAttribute('aria-label',`Ampliar foto: ${p[2]}`);let img=document.createElement('img');img.src=path(p[0]);img.alt=p[2];img.loading='lazy';let span=document.createElement('span');span.textContent=p[2];b.append(img,span);b.addEventListener('click',()=>{current=i;showPhoto();box.showModal();document.body.classList.add('modal-open')});return b}));more.hidden=expanded||shown.length<=9;more.textContent=`Ver todas as ${shown.length} fotos`}
function showPhoto(){let p=shown[current];document.querySelector('#large-photo').src=path(p[0]);document.querySelector('#large-photo').alt=p[2];document.querySelector('#photo-caption').textContent=`${p[2]} · ${current+1} de ${shown.length}`}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;expanded=false;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});renderGallery()}));more.addEventListener('click',()=>{expanded=true;renderGallery()});document.querySelector('.lightbox-close').addEventListener('click',()=>box.close());box.addEventListener('close',()=>document.body.classList.remove('modal-open'));box.addEventListener('click',e=>{if(e.target===box)box.close()});document.querySelector('#prev').addEventListener('click',()=>{current=(current-1+shown.length)%shown.length;showPhoto()});document.querySelector('#next').addEventListener('click',()=>{current=(current+1)%shown.length;showPhoto()});box.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){current=(current-1+shown.length)%shown.length;showPhoto()}if(e.key==='ArrowRight'){current=(current+1)%shown.length;showPhoto()}});renderGallery();
const menu=document.querySelector('.menu'),nav=document.querySelector('.header nav');menu.addEventListener('click',()=>{let open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Fechar menu':'Abrir menu')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menu')}));
const waBase='https://wa.me/5511954036891?text=';document.querySelectorAll('.whatsapp').forEach(a=>a.href=waBase+encodeURIComponent(a.dataset.message||'Olá, Flávio! Vi o site da casa em Bertioga e gostaria de consultar datas e valores para uma estadia.'));
const form=document.querySelector('#booking'),arrival=form.elements.arrival,departure=form.elements.departure;const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());arrival.min=today;departure.min=today;
arrival.addEventListener('change',()=>{if(arrival.value){const d=new Date(arrival.value+'T12:00:00');d.setDate(d.getDate()+1);departure.min=d.toISOString().slice(0,10);if(departure.value<=arrival.value)departure.value=''}departure.setCustomValidity('')});departure.addEventListener('change',()=>departure.setCustomValidity(''));
function formatDate(d){return d.split('-').reverse().join('/')}
form.addEventListener('submit',e=>{e.preventDefault();if(departure.value<=arrival.value){departure.setCustomValidity('A saída precisa ser depois da chegada.');departure.reportValidity();return}if(!form.reportValidity())return;let message=`Olá, Flávio! Vi o site da casa em Bertioga e gostaria de consultar disponibilidade e valores.\n\nChegada: ${formatDate(arrival.value)}\nSaída: ${formatDate(departure.value)}\nGrupo: ${form.elements.guests.value}\n\nPode me informar as condições da estadia?`;let link=waBase+encodeURIComponent(message);window.open(link,'_blank','noopener');const status=document.querySelector('#form-status');status.replaceChildren(document.createTextNode('Consulta preparada. '));let a=document.createElement('a');a.href=link;a.target='_blank';a.rel='noopener';a.textContent='Abrir conversa no WhatsApp';a.style.textDecoration='underline';status.append(a)});
