import { env } from 'cloudflare:workers';
import { z } from 'zod';
const player=z.object({id:z.string().uuid(),name:z.string().min(1).max(60),number:z.string().regex(/^[0-9]{1,3}$/),position:z.string().max(40),x:z.number().min(0).max(100),y:z.number().min(0).max(100),active:z.boolean()});
const event=z.object({id:z.string().uuid(),player:z.string().uuid(),action:z.string().min(1).max(40),result:z.enum(['success','error','neutral']),time:z.string().datetime(),period:z.string().regex(/^[1-5]$/)});
const match=z.object({id:z.string().uuid(),sport:z.enum(['volei','basquete','futebol']),team:z.string().min(1).max(60),opponent:z.string().max(60),date:z.string().datetime(),players:z.array(player).max(100),events:z.array(event).max(10000),finished:z.boolean(),period:z.string().regex(/^[1-5]$/),score:z.tuple([z.number().int().nonnegative(),z.number().int().nonnegative()])});
const payload=z.object({revision:z.number().int().nonnegative(),data:z.object({matches:z.array(match).max(200)})});
function db(){if(!env.DB)throw new Error('Storage unavailable');return env.DB;}
export async function GET(){try{const row=await db().prepare('SELECT data, revision FROM workspace WHERE id = ?').bind('coach').first<{data:string,revision:number}>();return Response.json(row?{data:JSON.parse(row.data),revision:row.revision}:{data:null,revision:0});}catch(e){console.error(e);return Response.json({error:'Não foi possível carregar seus dados. Tente novamente.'},{status:503});}}
export async function PUT(request:Request){try{const checked=payload.safeParse(await request.json());if(!checked.success)return Response.json({error:"Dados inválidos."},{status:400});const {data,revision}=checked.data;if(!data||!Array.isArray(data.matches)||!Number.isInteger(revision)||JSON.stringify(data).length>1500000)return Response.json({error:'Dados inválidos.'},{status:400});const json=JSON.stringify(data);if(revision===0){const result=await db().prepare('INSERT OR IGNORE INTO workspace (id, data, revision) VALUES (?, ?, 1)').bind('coach',json).run();if(result.meta.changes)return Response.json({revision:1});}const result=await db().prepare('UPDATE workspace SET data = ?, revision = revision + 1 WHERE id = ? AND revision = ?').bind(json,'coach',revision).run();if(!result.meta.changes)return Response.json({error:'Seus dados mudaram em outra aba. Recarregue antes de continuar.'},{status:409});return Response.json({revision:revision+1});}catch(e){console.error(e);return Response.json({error:'Não foi possível salvar. Seus dados continuam na tela; tente novamente.'},{status:503});}}
